"""Event payload models — compatibility barrel (C65).

Domain modules hold implementations; import those for new code:
- ``events_payloads_base`` — shared base types
- ``events_payloads_run`` — run lifecycle / model / hardware payloads
- ``events_payloads_stage`` — stage / finding / gate payloads
- ``events_payloads_campaign`` — campaign / stitch / slice payloads

This module re-exports all symbols for ``events.py`` star-import and legacy callers.
"""

from agent_core.models.events_payloads_base import (
    DEFAULT_FINDING_FIX_STRICTNESS,
    FINDING_FIX_STRICTNESS_CONTEXT_KEY,
    BasePayload,
    FindingFixStrictnessSettings,
    NetworkEgressPolicySnapshot,
    PolicySnapshotV1,
    RequiredFixArtifact,
    finding_severity_requires_fixes,
)
from agent_core.models.events_payloads_campaign import (
    CampaignCompletedPayload,
    CampaignCreatedPayload,
    CampaignFailedPayload,
    CampaignPausedPayload,
    CampaignPolicyPayload,
    CompletionEvaluatedPayload,
    DeliveryBacklogGeneratedPayload,
    DeliveryBacklogRevisedPayload,
    DomainCriticProposedPayload,
    EpicStatusChangedPayload,
    MaintenanceArchitecturePassedPayload,
    MaintenanceArchitectureStartedPayload,
    MaintenanceRefactorPassedPayload,
    MaintenanceRefactorStartedPayload,
    ResearchBriefEmittedPayload,
    ResearchBriefReviewPayload,
    ResearchBriefSourcePayload,
    ResearchPatternIndexedPayload,
    SliceDeferredPayload,
    SliceQueuedPayload,
    StitchAppliedPayload,
    StitchDependencyCheckedPayload,
    StitchFailedPayload,
    StitchLicenseCheckedPayload,
    StitchPlanEmittedPayload,
)
from agent_core.models.events_payloads_run import (
    HardwareProfileDetectedPayload,
    MemoryIndexedPayload,
    ModelBindingOverriddenPayload,
    ModelPreflightFailedPayload,
    ModelPreflightPassedPayload,
    ModelPreflightStartedPayload,
    ModelSelectedFallbackPayload,
    ModelSelectedPrimaryPayload,
    PersonaShelfUpdatedPayload,
    ResourcePressureWarnPayload,
    RunCompletedPayload,
    RunCreatedPayload,
    RunEscalatedPayload,
    RunFailedPayload,
    RunStartedPayload,
    WorkloadRoleClaimedPayload,
    WorkloadRoleReleasedPayload,
)
from agent_core.models.events_payloads_stage import (
    CriticVerdictEmittedPayload,
    FindingClosedPayload,
    FindingCreatedPayload,
    FindingRoutedPayload,
    GateDecisionEmittedPayload,
    GateOverriddenPayload,
    MemoryRetrievalEmittedPayload,
    SelfRefinementLoopSignalledPayload,
    StageBlockedPayload,
    StageFailedPayload,
    StagePassedPayload,
    StageStartedPayload,
)

__all__ = [
    "DEFAULT_FINDING_FIX_STRICTNESS",
    "FINDING_FIX_STRICTNESS_CONTEXT_KEY",
    "BasePayload",
    "CampaignCompletedPayload",
    "CampaignCreatedPayload",
    "CampaignFailedPayload",
    "CampaignPausedPayload",
    "CampaignPolicyPayload",
    "CompletionEvaluatedPayload",
    "CriticVerdictEmittedPayload",
    "DeliveryBacklogGeneratedPayload",
    "DeliveryBacklogRevisedPayload",
    "DomainCriticProposedPayload",
    "EpicStatusChangedPayload",
    "FindingClosedPayload",
    "FindingCreatedPayload",
    "FindingFixStrictnessSettings",
    "FindingRoutedPayload",
    "GateDecisionEmittedPayload",
    "GateOverriddenPayload",
    "HardwareProfileDetectedPayload",
    "MaintenanceArchitecturePassedPayload",
    "MaintenanceArchitectureStartedPayload",
    "MaintenanceRefactorPassedPayload",
    "MaintenanceRefactorStartedPayload",
    "MemoryIndexedPayload",
    "MemoryRetrievalEmittedPayload",
    "ModelBindingOverriddenPayload",
    "ModelPreflightFailedPayload",
    "ModelPreflightPassedPayload",
    "ModelPreflightStartedPayload",
    "ModelSelectedFallbackPayload",
    "ModelSelectedPrimaryPayload",
    "NetworkEgressPolicySnapshot",
    "PersonaShelfUpdatedPayload",
    "PolicySnapshotV1",
    "RequiredFixArtifact",
    "ResearchBriefEmittedPayload",
    "ResearchBriefReviewPayload",
    "ResearchBriefSourcePayload",
    "ResearchPatternIndexedPayload",
    "ResourcePressureWarnPayload",
    "RunCompletedPayload",
    "RunCreatedPayload",
    "RunEscalatedPayload",
    "RunFailedPayload",
    "RunStartedPayload",
    "SelfRefinementLoopSignalledPayload",
    "SliceDeferredPayload",
    "SliceQueuedPayload",
    "StageBlockedPayload",
    "StageFailedPayload",
    "StagePassedPayload",
    "StageStartedPayload",
    "StitchAppliedPayload",
    "StitchDependencyCheckedPayload",
    "StitchFailedPayload",
    "StitchLicenseCheckedPayload",
    "StitchPlanEmittedPayload",
    "WorkloadRoleClaimedPayload",
    "WorkloadRoleReleasedPayload",
    "finding_severity_requires_fixes",
]
