apiVersion: v1
kind: Secret
metadata:
  name: nimbusware-api-secrets
type: Opaque
stringData:
  NIMBUSWARE_DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  NIMBUSWARE_ADMIN_TOKEN: {{ .Values.secrets.adminToken | quote }}
