apiVersion: v1
kind: Service
metadata:
  name: nimbusware-api
spec:
  selector:
    app: nimbusware-api
  ports:
    - port: {{ .Values.api.servicePort }}
      targetPort: {{ .Values.api.servicePort }}
