from __future__ import annotations

from env.settings_catalog import SettingDef, SettingKind, SettingScope


def core_legacy_install_defs() -> tuple[SettingDef, ...]:

    install = SettingScope.INSTALL
    b = SettingKind.BOOL
    i = SettingKind.INT
    s = SettingKind.STR
    e = SettingKind.ENUM

    return (
        SettingDef(
            "NIMBUSWARE_DATABASE_URL",
            install,
            s,
            "",
            "Postgres URL",
            "Event store and config authority. Set in .env only.",
            "Install — infrastructure",
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_REPO_ROOT",
            install,
            s,
            "",
            "Repository root",
            "Path to Nimbusware install. Set in .env only.",
            "Install — infrastructure",
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_CLONE_URL",
            install,
            s,
            "https://github.com/tycheung/nimbusware.git",
            "Clone URL",
            "Git remote used by the desktop launcher install flow.",
            "Install — infrastructure",
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_ADMIN_TOKEN",
            install,
            s,
            "",
            "Admin API token",
            "Secret for Admin Console and admin API routes. Set in .env only.",
            "Install — secrets",
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_API_KEY",
            install,
            s,
            "",
            "Enterprise API key",
            "Enterprise Maker user key. Set in .env only.",
            "Install — secrets",
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_AUDIT_EXPORT_SIGNING_KEY",
            install,
            s,
            "",
            "Audit bundle HMAC key",
            "Signs run audit export tarballs.",
            "Install — secrets",
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_PROVIDER_VAULT_KEY",
            install,
            s,
            "",
            "Provider connection vault key",
            "Encrypts API keys in nimbusware_provider_connection. Falls back to admin token.",
            "Install — secrets",
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_EDITION",
            install,
            e,
            "individual",
            "Product edition",
            "individual or enterprise. Set at install.",
            "Install — infrastructure",
            choices=("individual", "enterprise"),
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_INSTALL_PROFILE",
            install,
            e,
            "recommended",
            "Install profile",
            "recommended (Ollama + default pulls) or barebones (minimal).",
            "Install — infrastructure",
            choices=("recommended", "barebones"),
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_SETUP_BUNDLE",
            install,
            e,
            "default",
            "Setup bundle",
            "default (Individual safe-lean) or enterprise (strict env + fleet seeds).",
            "Install — infrastructure",
            choices=("default", "enterprise"),
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_DEFAULT_AUTOPILOT_PROFILE",
            install,
            s,
            "guided",
            "Default autopilot profile id",
            "Applied on first Maker launch when unset in localStorage.",
            "Install — defaults",
            admin_editable=True,
            user_editable=True,
        ),
        SettingDef(
            "NIMBUSWARE_DEFAULT_ENFORCEMENT_PROFILE",
            install,
            s,
            "balanced",
            "Default enforcement profile id",
            "Applied on first Maker launch when unset in localStorage.",
            "Install — defaults",
            admin_editable=True,
            user_editable=True,
        ),
        SettingDef(
            "NIMBUSWARE_DEFAULT_WORKFLOW_PROFILE",
            install,
            s,
            "micro_slice",
            "Default workflow profile",
            "Applied on first Maker launch when unset in localStorage.",
            "Install — defaults",
            admin_editable=True,
            user_editable=True,
        ),
        SettingDef(
            "NIMBUSWARE_OPERATOR_PRESET",
            install,
            s,
            "",
            "Operator environment preset",
            "Apply offline, local-llm, or production transport defaults at startup.",
            "Install — operator presets",
            admin_editable=True,
            user_editable=True,
        ),
        SettingDef(
            "NIMBUSWARE_OIDC_ENABLED",
            install,
            b,
            "0",
            "OIDC SSO for consoles",
            "Enable enterprise Admin Console OIDC login gate.",
            "Install — enterprise SSO",
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_OIDC_ISSUER",
            install,
            s,
            "",
            "OIDC issuer URL",
            "IdP issuer base URL (authorize/token endpoints under this host).",
            "Install — enterprise SSO",
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_OIDC_CLIENT_ID",
            install,
            s,
            "",
            "OIDC client ID",
            "Registered OIDC client for Admin Console.",
            "Install — enterprise SSO",
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_OIDC_CLIENT_SECRET",
            install,
            s,
            "",
            "OIDC client secret",
            "Optional for PKCE public clients.",
            "Install — secrets",
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_AUDIT_RETENTION_DAYS",
            install,
            i,
            "90",
            "Audit retention days",
            "Default window for enterprise SOC2-oriented audit export.",
            "Install — enterprise audit",
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_EVENT_STORE_RETENTION_DAYS",
            install,
            i,
            "0",
            "Event store retention days",
            "Future purge window for event_store rows; 0 disables automated purge.",
            "Install — event store",
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_EVENT_STORE_LEGAL_HOLD",
            install,
            b,
            "0",
            "Event store legal hold",
            "When set, retention purge is blocked regardless of retention days.",
            "Install — event store",
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_EVENT_STORE_PURGE_EXECUTE",
            install,
            b,
            "0",
            "Event store purge execute",
            "Allow DELETE in purge_event_store_retention.py when append-only triggers are lifted.",
            "Install — event store",
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_OIDC_REDIRECT_URI",
            install,
            s,
            "",
            "OIDC redirect URI",
            "Callback URL registered with IdP (defaults from NIMBUSWARE_ADMIN_CONSOLE_URL).",
            "Install — enterprise SSO",
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_SUBSCRIPTION_OAUTH_ISSUER",
            install,
            s,
            "",
            "Desktop subscription OAuth issuer",
            "OIDC issuer for Auth0/Okta/Keycloak desktop subscription connect (e.g. https://tenant.auth0.com).",
            "Install — desktop subscriptions",
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_SUBSCRIPTION_OAUTH_CLIENT_ID",
            install,
            s,
            "",
            "Desktop subscription OAuth client ID",
            "Registered OAuth client for desktop subscription redirect flow.",
            "Install — desktop subscriptions",
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_SUBSCRIPTION_OAUTH_CLIENT_SECRET",
            install,
            s,
            "",
            "Desktop subscription OAuth client secret",
            "Optional for PKCE public clients; required for confidential clients.",
            "Install — secrets",
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_SUBSCRIPTION_OAUTH_REDIRECT_URI",
            install,
            s,
            "",
            "Desktop subscription OAuth redirect URI",
            "Callback URL registered with IdP (defaults from NIMBUSWARE_API_BASE).",
            "Install — desktop subscriptions",
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_SUBSCRIPTION_OAUTH_SCOPES",
            install,
            s,
            "openid profile offline_access",
            "Desktop subscription OAuth scopes",
            "Space-separated scopes for subscription OAuth authorize URL.",
            "Install — desktop subscriptions",
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_API_BASE",
            install,
            s,
            "http://127.0.0.1:8000/v1",
            "API base URL",
            "Maker/Admin → API URL. Set in .env only.",
            "Install — infrastructure",
            admin_editable=False,
            user_editable=False,
        ),
        SettingDef(
            "NIMBUSWARE_UI_BACKEND",
            install,
            s,
            "web",
            "Desktop UI backend",
            "web = pywebview opens /v1/maker/app or /v1/admin/app (default).",
            "Install — infrastructure",
            admin_editable=False,
            user_editable=False,
        ),
    )
