from __future__ import annotations

from env.settings_catalog import SettingDef
from env.settings_catalog_extended._factories import (
    _BOOL,
    _INT,
    _STR,
    _USER,
)


def user_defs() -> tuple[SettingDef, ...]:
    return (
        SettingDef(
            "NIMBUSWARE_SLICE_P3_EVIDENCE",
            _USER,
            _BOOL,
            "1",
            "Slice P3 evidence",
            "Emit P3 evidence stages during slice implement.",
            "User — maker runtime",
        ),
        SettingDef(
            "NIMBUSWARE_SLICE_BRANCH_PREFIX",
            _USER,
            _STR,
            "nimbusware/run-",
            "Git branch prefix",
            "Prefix for auto-created git branches.",
            "User — git outputs",
        ),
        SettingDef(
            "NIMBUSWARE_SLICE_REPO_MAP_ENABLED",
            _USER,
            _BOOL,
            "1",
            "Slice repo map enabled",
            "Inject repo tree + import graph into slice context packets.",
            "User — maker runtime",
        ),
        SettingDef(
            "NIMBUSWARE_SLICE_LSP_ENABLED",
            _USER,
            _BOOL,
            "1",
            "Slice Pyright LSP symbols",
            "When enabled, try pyright-langserver documentSymbol before AST symbol sketch.",
            "User — maker runtime",
        ),
        SettingDef(
            "NIMBUSWARE_SLICE_LSP_COMMAND",
            _USER,
            _STR,
            "",
            "Slice LSP command",
            "Override langserver argv (e.g. pyright-langserver or npx pyright-langserver).",
            "User — maker runtime",
        ),
        SettingDef(
            "NIMBUSWARE_SLICE_LSP_TIMEOUT_SEC",
            _USER,
            _INT,
            "8",
            "Slice LSP timeout (sec)",
            "Per-request timeout; hung servers fall back to AST sketch.",
            "User — maker runtime",
        ),
        SettingDef(
            "NIMBUSWARE_READ_MAX_CHARS",
            _USER,
            _INT,
            "16000",
            "Read tool max chars",
            "Max characters returned by the agent read tool.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_SHELL_OUTPUT_MAX_CHARS",
            _USER,
            _INT,
            "4000",
            "Shell output max chars",
            "Max characters of shell command output in agent tool results.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_TOOL_OFFLOAD_CHARS",
            _USER,
            _INT,
            "5000",
            "Tool output offload threshold",
            "Spill single tool results larger than this to workspace cache with preview.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_JIT_MICROCOMPACT_TURNS",
            _USER,
            _INT,
            "8",
            "JIT microcompact keep turns",
            "Keep last N tool results verbatim when microcompacting agent loop history.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_JIT_MICROCOMPACT_TOKEN_THRESHOLD",
            _USER,
            _INT,
            "12000",
            "JIT microcompact token threshold",
            "Estimated loop tokens before clearing older tool results.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_CONTEXT_DEDUP",
            _USER,
            _STR,
            "balanced",
            "Context dedup mode",
            "Supersede duplicate tool results: off, balanced, compact, or verbose.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_AGENT_CONTEXT_WINDOW",
            _USER,
            _INT,
            "32000",
            "Agent context window tokens",
            "Estimated role context window for full compact trigger.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_READ_OUTLINE_MIN_LINES",
            _USER,
            _INT,
            "200",
            "Read outline min lines",
            "Use outline mode for non-target Python files at or above this line count.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_MEMORY_INDEX_FIRST",
            _USER,
            _BOOL,
            "1",
            "Memory index-first injection",
            "Inject compact memory index table instead of full retrieval excerpts by default.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_AGENT_JIT_LOOP",
            _USER,
            _BOOL,
            "1",
            "Agent JIT tool loop",
            "Multi-turn tool loop for slice implement agent mode (vs single-shot plan).",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_AGENT_TOOLS",
            _USER,
            _STR,
            "read,write,edit,grep,shell",
            "Agent tool allowlist",
            "Comma-separated tools exposed to slice implement agent (optional: find, ls).",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_PROJECTION_PRUNE_AGENT_TOOLS",
            _USER,
            _BOOL,
            "1",
            "Prune agent tool outputs in projections",
            "Replace stale agent tool log lines in theater/timeline with pruned placeholders.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_HANDOFF_LLM_SUMMARY",
            _USER,
            _BOOL,
            "0",
            "Handoff LLM summary",
            "When enabled, optionally refine handoff text via LLM (default deterministic).",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_CAMPAIGN_COMPACT_ENABLED",
            _USER,
            _BOOL,
            "1",
            "Campaign compaction",
            "Summarize older slice handoffs to bound planner context in long runs.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_AGENT_COMPACT",
            _USER,
            _BOOL,
            "1",
            "Manual run compaction",
            "Allow POST /v1/runs/{id}/compact and MCP nimbusware_compact_run.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_CAMPAIGN_KEEP_RECENT_TOKENS",
            _USER,
            _INT,
            "12000",
            "Campaign keep recent tokens",
            "Verbatim recent handoff token budget; defaults from hardware profile when unset.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_CAMPAIGN_RESERVE_TOKENS",
            _USER,
            _INT,
            "8000",
            "Campaign reserve tokens",
            "Output reservation subtracted from keep-recent window.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_CAMPAIGN_PARALLEL_SLICES",
            _USER,
            _INT,
            "1",
            "Campaign parallel slices per tick",
            "Max independent backlog slices queued per campaign tick; mesh assigns across compute nodes when >1.",
            "User — campaign throughput",
        ),
        SettingDef(
            "NIMBUSWARE_MEMORY_RETRIEVAL_K",
            _USER,
            _INT,
            "5",
            "Memory retrieval top-k",
            "Max memory chunks injected per slice (workflow YAML may override).",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_CONTEXT_ARTIFACT_FAISS_REBUILD",
            _USER,
            _BOOL,
            "0",
            "Rebuild FAISS after context-artifact bridge",
            "Rebuild memory FAISS index after context-artifact bridge-memory.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_AXE_ENABLED",
            _USER,
            _BOOL,
            "0",
            "Axe-core in human-fidelity suite",
            "Run axe-core accessibility rule packs during human-fidelity checks.",
            "User — maker runtime",
        ),
        SettingDef(
            "NIMBUSWARE_MOUSE_FIDELITY",
            _USER,
            _BOOL,
            "0",
            "Mouse wheel/hover in human-fidelity suite",
            "Run optional Playwright wheel and hover smoke during human-fidelity checks.",
            "User — maker runtime",
        ),
        SettingDef(
            "NIMBUSWARE_SWE_BENCH_ENABLED",
            _USER,
            _BOOL,
            "1",
            "micro_slice regression harness enabled",
            "When off, swe_bench_harness.py exits 0 without running.",
            "User — benchmarks",
        ),
        SettingDef(
            "NIMBUSWARE_SWE_BENCH_MANIFEST",
            _USER,
            _STR,
            "",
            "micro_slice regression manifest path",
            "Path to swe_bench manifest JSON (default: tests/fixtures/swe_bench/manifest.json).",
            "User — benchmarks",
        ),
        SettingDef(
            "NIMBUSWARE_MAX_PARALLEL_WRITERS",
            _USER,
            _INT,
            "",
            "Max parallel writers",
            "Override hardware governor parallel writer cap.",
            "User — hardware governor",
        ),
        SettingDef(
            "NIMBUSWARE_ALLOW_PARALLEL_CRITICS",
            _USER,
            _BOOL,
            "0",
            "Allow parallel critics",
            "Allow critics to run in parallel under governor.",
            "User — hardware governor",
        ),
        SettingDef(
            "NIMBUSWARE_RESERVE_RAM_GB",
            _USER,
            _INT,
            "2",
            "Reserve RAM GB",
            "RAM reserved for OS outside governor cap.",
            "User — hardware governor",
        ),
        SettingDef(
            "NIMBUSWARE_SLICE_REPLAN_MAX",
            _USER,
            _INT,
            "",
            "Slice replan max attempts",
            "Max replan attempts per slice.",
            "User — maker runtime",
        ),
        SettingDef(
            "NIMBUSWARE_SLICE_STUB_LOC_PER_FILE",
            _USER,
            _INT,
            "",
            "Slice stub LOC per file",
            "Stub implement LOC budget per file.",
            "User — maker runtime",
        ),
    )
