from __future__ import annotations

import asyncio
import hashlib
import os
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Literal
from urllib.parse import urlparse
from uuid import UUID, uuid4

import httpx

from agent_core.critique_stages import (
    FRONTEND_WRITER_CRITIQUE_STAGE,
    IMPLEMENTATION_CRITIQUE_STAGE,
    MODULE_INTEGRATOR_CRITIQUE_STAGE,
    PLANNER_CRITIQUE_STAGE,
    TEST_WRITER_CRITIQUE_STAGE,
)
from agent_core.mapping import mapping_or_empty
from agent_core.models import (
    EventType,
    FindingCreatedEvent,
    FindingCreatedPayload,
    FindingFixStrictnessSettings,
    GateDecisionEmittedEvent,
    GateDecisionEmittedPayload,
    ModelPreflightPassedEvent,
    ModelPreflightPassedPayload,
    ModelPreflightStartedEvent,
    ModelPreflightStartedPayload,
    ModelSelectedFallbackEvent,
    ModelSelectedFallbackPayload,
    ModelSelectedPrimaryEvent,
    ModelSelectedPrimaryPayload,
    RunCreatedEvent,
    RunCreatedPayload,
    RunStartedEvent,
    RunStartedPayload,
    SelfRefinementLoopSignalledEvent,
    SelfRefinementLoopSignalledPayload,
    Severity,
    StageFailedEvent,
    StageFailedPayload,
    StagePassedEvent,
    StagePassedPayload,
    StageStartedEvent,
    StageStartedPayload,
    Verdict,
    validate_event_dict,
)
from nimbusware_env.env_flags import (
    env_str,
    env_tri_state,
    env_truthy,
    nimbusware_outbound_fetch_enabled,
    nimbusware_use_llm_enabled,
)
from nimbusware_executor.fetch import EgressResponseTooLarge
from nimbusware_extensions import SelfRefinementPolicy, load_self_refinement_policy
from nimbusware_extensions.phase2 import AgentEvaluator, agent_evaluator_score_band
from nimbusware_extensions.self_refinement import SelfRefinementEvaluator
from nimbusware_orchestrator._pipeline._helpers_runtime import (
    _SELF_REFINEMENT_MAX_ITER_REASON,
    _SELF_REFINEMENT_POLICY_STAGE,
    _agent_evaluator_auto_create_env_disabled,
    _agent_evaluator_auto_promote_env_disabled,
    _coerce_samples_ms,
    _last_self_refinement_loop_should_continue,
    _persona_id_from_assignment_slot,
    _self_refinement_auto_promote_env_disabled,
    _self_refinement_marker_count,
    _self_refinement_max_iterations_exceeded,
    _self_refinement_stage_marker_env_disabled,
    gate_fail_for_stage,
    ollama_runtime_from_host,
    optional_meta_section,
    optional_rows_and_profile,
    optional_stage_yaml_gate,
    optional_tri_allows_emit,
)

__all__ = (
    "AgentEvaluator",
    "Any",
    "EgressResponseTooLarge",
    "EventType",
    "FRONTEND_WRITER_CRITIQUE_STAGE",
    "FindingCreatedEvent",
    "FindingCreatedPayload",
    "FindingFixStrictnessSettings",
    "GateDecisionEmittedEvent",
    "GateDecisionEmittedPayload",
    "IMPLEMENTATION_CRITIQUE_STAGE",
    "Literal",
    "MODULE_INTEGRATOR_CRITIQUE_STAGE",
    "ModelPreflightPassedEvent",
    "ModelPreflightPassedPayload",
    "ModelPreflightStartedEvent",
    "ModelPreflightStartedPayload",
    "ModelSelectedFallbackEvent",
    "ModelSelectedFallbackPayload",
    "ModelSelectedPrimaryEvent",
    "ModelSelectedPrimaryPayload",
    "PLANNER_CRITIQUE_STAGE",
    "Path",
    "RunCreatedEvent",
    "RunCreatedPayload",
    "RunStartedEvent",
    "RunStartedPayload",
    "SelfRefinementEvaluator",
    "SelfRefinementLoopSignalledEvent",
    "SelfRefinementLoopSignalledPayload",
    "SelfRefinementPolicy",
    "Severity",
    "StageFailedEvent",
    "StageFailedPayload",
    "StagePassedEvent",
    "StagePassedPayload",
    "StageStartedEvent",
    "StageStartedPayload",
    "TEST_WRITER_CRITIQUE_STAGE",
    "UUID",
    "Verdict",
    "_SELF_REFINEMENT_MAX_ITER_REASON",
    "_SELF_REFINEMENT_POLICY_STAGE",
    "_agent_evaluator_auto_create_env_disabled",
    "_agent_evaluator_auto_promote_env_disabled",
    "_coerce_samples_ms",
    "_last_self_refinement_loop_should_continue",
    "_persona_id_from_assignment_slot",
    "_self_refinement_auto_promote_env_disabled",
    "_self_refinement_marker_count",
    "_self_refinement_max_iterations_exceeded",
    "_self_refinement_stage_marker_env_disabled",
    "agent_evaluator_score_band",
    "annotations",
    "asyncio",
    "datetime",
    "env_str",
    "env_tri_state",
    "env_truthy",
    "gate_fail_for_stage",
    "hashlib",
    "httpx",
    "load_self_refinement_policy",
    "mapping_or_empty",
    "nimbusware_outbound_fetch_enabled",
    "nimbusware_use_llm_enabled",
    "ollama_runtime_from_host",
    "optional_meta_section",
    "optional_rows_and_profile",
    "optional_stage_yaml_gate",
    "optional_tri_allows_emit",
    "os",
    "time",
    "timezone",
    "urlparse",
    "uuid4",
    "validate_event_dict",
)
