"""Target adapter file generation for Integration Adapter Writer live path."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any
from uuid import UUID

from nimbusware_orchestrator.workflow_integration_adapter_writer import (
    DEFAULT_ADAPTER_KIND,
    IntegrationAdapterWriterWorkflowBlock,
)

_KNOWN_ADAPTER_KINDS = frozenset({"api_bridge", "compatibility_shim"})
_KIND_PATTERN = re.compile(r"^[a-z][a-z0-9_-]{0,63}$")

_ADAPTER_MODULE_TEMPLATE = '''"""Nimbusware-generated integration adapter ({kind}).

Run: {run_id}
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


class {class_name}:
    """Target adapter for ``{kind}`` (generated)."""

    kind: str = "{kind}"

    def __init__(self, workspace_dir: Path, *, run_id: str) -> None:
        self._workspace_dir = workspace_dir
        self._run_id = run_id

    def connect(self) -> bool:
        state_path = self._workspace_dir / "target_state.json"
        if not state_path.is_file():
            return False
        try:
            raw = json.loads(state_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return False
        return raw.get("connected") is True

    def describe(self) -> dict[str, Any]:
        return {{"kind": self.kind, "run_id": self._run_id}}

    def sync_target(self) -> dict[str, Any]:
        """Perform target-specific integration I/O (local workspace)."""
        raise NotImplementedError
'''

_README_TEMPLATE = """# Integration adapter workspace

- **Run ID:** `{run_id}`
- **Target kind:** `{kind}`
- **Module:** `{module_name}`

Generated by Nimbusware Integration Adapter Writer.
"""


def _class_name_for_kind(kind: str) -> str:
    parts = [p for p in kind.replace("-", "_").split("_") if p]
    base = "".join(p[:1].upper() + p[1:] for p in parts) or "Compatibility"
    return f"{base}Adapter"


def _target_state_for_kind(kind: str, run_id: str) -> dict[str, Any]:
    if kind == "api_bridge":
        return {
            "connected": True,
            "transport": "http",
            "endpoint": "http://127.0.0.1:8080/health",
            "run_id": run_id,
        }
    if kind == "compatibility_shim":
        return {
            "connected": True,
            "shim_mode": "bundle_compatibility",
            "run_id": run_id,
        }
    return {"connected": True, "kind": kind, "run_id": run_id}


def probe_http_endpoint(url: str, *, timeout: float = 2.0) -> dict[str, Any]:
    import httpx

    try:
        resp = httpx.get(url, timeout=timeout, follow_redirects=True)
    except httpx.HTTPError as exc:
        return {"reachable": False, "error": str(exc)[:200]}
    return {
        "reachable": True,
        "status_code": resp.status_code,
        "ok": resp.is_success,
        "content_type": resp.headers.get("content-type", ""),
        "body_preview": resp.text[:200],
    }


def validate_integration_manifest(manifest: dict[str, Any]) -> list[str]:
    """Return validation errors; empty when manifest is acceptable."""
    errors: list[str] = []
    if not str(manifest.get("run_id", "")).strip():
        errors.append("run_id required")
    kind = str(manifest.get("target_adapter_kind", "")).strip()
    if not kind:
        errors.append("target_adapter_kind required")
    elif not _KIND_PATTERN.match(kind):
        errors.append("target_adapter_kind must be lowercase alphanumeric with _ or -")
    elif kind not in _KNOWN_ADAPTER_KINDS:
        errors.append(f"unknown target_adapter_kind: {kind!r}")
    if manifest.get("stub_only") is True:
        errors.append("stub_only manifest cannot run live integration")
    schema_ver = manifest.get("schema_version")
    if schema_ver is not None:
        if isinstance(schema_ver, bool) or not isinstance(schema_ver, int) or schema_ver < 1:
            errors.append("schema_version must be an integer >= 1 when present")
    return errors


def validate_manifest_for_run(
    manifest: dict[str, Any],
    *,
    run_id: str,
    kind: str,
) -> list[str]:
    """Cross-check manifest fields against the active run and adapter kind."""
    errors = list(validate_integration_manifest(manifest))
    manifest_run = str(manifest.get("run_id", "")).strip()
    if manifest_run and manifest_run != run_id:
        errors.append("manifest run_id does not match active run")
    manifest_kind = str(manifest.get("target_adapter_kind", "")).strip()
    if manifest_kind and manifest_kind != kind:
        errors.append("manifest target_adapter_kind does not match workflow kind")
    return errors


def execute_target_adapter_integration(
    abs_dir: Path,
    *,
    kind: str,
    run_id: str,
) -> dict[str, Any]:
    """Write ``target_state.json`` and run in-process adapter sync (real local I/O)."""
    manifest_path = abs_dir / "manifest.json"
    if manifest_path.is_file():
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return {
                "target_integration_status": "manifest_invalid",
                "target_state_path": "target_state.json",
            }
        errs = validate_manifest_for_run(manifest, run_id=run_id, kind=kind)
        if errs:
            return {
                "target_integration_status": "manifest_rejected",
                "validation_errors": errs,
            }
    state_path = abs_dir / "target_state.json"
    backup: str | None = None
    if state_path.is_file():
        backup = state_path.read_text(encoding="utf-8")
    state = _target_state_for_kind(kind, run_id)
    state_path.write_text(json.dumps(state, indent=2) + "\n", encoding="utf-8")

    module_name = f"adapter_{kind.replace('-', '_')}"
    mod_path = abs_dir / f"{module_name}.py"
    if not mod_path.is_file():
        return {
            "target_integration_status": "module_missing",
            "target_state_path": "target_state.json",
        }

    ns: dict[str, Any] = {}
    exec(mod_path.read_text(encoding="utf-8"), ns)  # noqa: S102 — generated workspace code
    cls_name = _class_name_for_kind(kind)
    adapter_cls = ns.get(cls_name)
    if adapter_cls is None:
        return {
            "target_integration_status": "class_missing",
            "target_state_path": "target_state.json",
        }
    adapter = adapter_cls(abs_dir, run_id=run_id)
    try:
        result = adapter.sync_target()
    except Exception as exc:  # noqa: BLE001 — rollback local target state
        if backup is not None:
            state_path.write_text(backup, encoding="utf-8")
        else:
            state_path.unlink(missing_ok=True)
        return {
            "target_integration_status": "rolled_back",
            "rollback_reason": str(exc)[:200],
            "target_state_path": "target_state.json",
        }
    if not adapter.connect():
        if backup is not None:
            state_path.write_text(backup, encoding="utf-8")
        return {
            "target_integration_status": "rolled_back",
            "rollback_reason": "connect_failed_after_sync",
            "target_state_path": "target_state.json",
        }
    result_payload: dict[str, Any] = {
        "target_integration_status": "integrated",
        "target_state_path": "target_state.json",
        "target_sync_result": result,
        "target_connected": True,
        "sync_artifact_paths": _sync_artifact_paths(abs_dir, kind),
    }
    if kind == "api_bridge":
        endpoint = str(state.get("endpoint") or "").strip()
        if endpoint:
            probe = probe_http_endpoint(endpoint)
            result_payload["http_probe"] = probe
            if probe.get("reachable"):
                state["last_http_probe"] = {
                    "status_code": probe.get("status_code"),
                    "ok": probe.get("ok"),
                    "content_type": probe.get("content_type"),
                }
                state_path.write_text(json.dumps(state, indent=2) + "\n", encoding="utf-8")
    return result_payload


def _sync_artifact_paths(abs_dir: Path, kind: str) -> list[str]:
    names: list[str] = []
    if kind == "compatibility_shim" and (abs_dir / "bundle_shim_map.json").is_file():
        names.append("bundle_shim_map.json")
    if (abs_dir / "target_state.json").is_file():
        names.append("target_state.json")
    return names


def write_integration_adapter_scaffold(
    repo_root: Path,
    run_id: UUID,
    block: IntegrationAdapterWriterWorkflowBlock,
) -> dict[str, Any]:
    """Write manifest + adapter module + README; run target integration I/O."""
    kind = block.target_adapter_kind or DEFAULT_ADAPTER_KIND
    rel_dir = Path(".nimbusware") / "integration_adapter_writer" / str(run_id)
    abs_dir = repo_root / rel_dir
    abs_dir.mkdir(parents=True, exist_ok=True)

    manifest = {
        "run_id": str(run_id),
        "target_adapter_kind": kind,
        "stub_only": block.stub_only,
    }
    manifest_rel = rel_dir / "manifest.json"
    manifest_abs = repo_root / manifest_rel
    manifest_abs.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    class_name = _class_name_for_kind(kind)
    module_name = f"adapter_{kind.replace('-', '_')}.py"
    module_rel = rel_dir / module_name
    module_abs = repo_root / module_rel

    sync_body = _sync_target_body(kind)
    module_src = _ADAPTER_MODULE_TEMPLATE.format(
        kind=kind,
        run_id=str(run_id),
        class_name=class_name,
    ).replace(
        "        raise NotImplementedError",
        sync_body,
    )
    module_abs.write_text(module_src, encoding="utf-8")

    readme_rel = rel_dir / "README.md"
    readme_abs = repo_root / readme_rel
    readme_abs.write_text(
        _README_TEMPLATE.format(
            run_id=str(run_id),
            kind=kind,
            module_name=module_name,
        ),
        encoding="utf-8",
    )

    integration: dict[str, Any] = {}
    if not block.stub_only:
        integration = execute_target_adapter_integration(
            abs_dir,
            kind=kind,
            run_id=str(run_id),
        )

    return {
        "workspace_manifest_path": str(manifest_rel).replace("\\", "/"),
        "workspace_manifest_bytes": manifest_abs.stat().st_size,
        "adapter_module_path": str(module_rel).replace("\\", "/"),
        "adapter_module_bytes": module_abs.stat().st_size,
        "adapter_readme_path": str(readme_rel).replace("\\", "/"),
        "adapter_generation_status": (
            "target_integrated"
            if integration.get("target_integration_status") == "integrated"
            else "scaffold_written"
        ),
        "target_adapter_kind": kind,
        **integration,
    }


def _sync_target_body(kind: str) -> str:
    if kind == "api_bridge":
        return (
            '        state_path = self._workspace_dir / "target_state.json"\n'
            "        payload = {\n"
            '            "connected": True,\n'
            '            "action": "probe",\n'
            '            "endpoint": "http://127.0.0.1:8080/health",\n'
            "        }\n"
            "        state_path.write_text(__import__('json').dumps(payload, indent=2), encoding='utf-8')\n"
            "        return payload\n"
        )
    if kind == "compatibility_shim":
        return (
            '        mapping_path = self._workspace_dir / "bundle_shim_map.json"\n'
            '        payload = {"mapped": True, "shim_mode": "bundle_compatibility"}\n'
            "        mapping_path.write_text(__import__('json').dumps(payload, indent=2), encoding='utf-8')\n"
            "        return payload\n"
        )
    return '        return {"action": "noop", "kind": self.kind}\n'
