// Generated by scripts/openapi_to_ts.py — expand via openapi-typescript when needed.
export type RunSummary = {
  status: string;
  workflow_profile?: string | null;
  event_count: number;
  latest_event_type: string;
  terminal_event_type?: string | null;
  findings_count: number;
  has_escalation: boolean;
  run_created_metadata?: Record<string, unknown>;
  persona_assignment?: Record<string, unknown> | null;
};

export type RunsListResponse = {
  run_ids?: string[];
  total?: number;
  has_more?: boolean;
  limit?: number;
  offset?: number;
  order?: "newest_first" | "oldest_first";
  include_summary?: number;
  workflow_profile?: string | null;
  workflow_profile_prefix?: string | null;
  created_after?: string | null;
  created_before?: string | null;
  has_escalation?: number | null;
  summaries?: Record<string, RunSummary>;
  next_cursor?: string | null;
  status?: string | null;
  runs?: RunSummary[];
  items?: RunSummary[];
};

export type PolicyDiffResponse = {
  run_a: string;
  run_b: string;
  identical: boolean;
  changed_count: number;
  changed: Record<string, unknown>[];
  gate_outcome?: Record<string, unknown> | null;
};
