// Generated by scripts/openapi_to_ts.py — expand via openapi-typescript when needed.
export type RunSummary = {
  run_id: string;
  status?: string;
  workflow_profile?: string;
  created_at?: string;
};

export type RunsListResponse = {
  runs?: RunSummary[];
  items?: RunSummary[];
  next_cursor?: string | null;
};
