from __future__ import annotations

from nimbusware_console.explainer_core.workflow_exports import WorkflowExplainerExports

_exp = WorkflowExplainerExports("universal_critique")
_universal_critique_explainer_cell = _exp.cell
universal_critique_export_filename_slug = _exp.export_filename_slug
universal_critique_explainer_table_rows = _exp.explainer_table_rows
universal_critique_explainer_export_json = _exp.explainer_export_json
universal_critique_explainer_table_rows_csv = _exp.explainer_table_rows_csv
