"""Run escalated Streamlit display (rows, captions, metrics)."""

from __future__ import annotations

from nimbusware_console.run_escalated.rows import (
    run_escalated_from_timeline,
    run_escalated_summary_rows,
    run_escalated_summary_rows_csv,
    run_escalated_export_json,
    run_escalated_export_filename_slug,
    run_escalated_history_from_timeline,
    run_escalated_history_table_rows,
    run_escalated_history_table_rows_csv,
    run_escalated_history_export_json,
    run_escalated_history_export_filename_slug,
    run_escalated_delta_from_timeline,
    run_escalated_delta_summary_rows,
    run_escalated_delta_table_rows_csv,
    run_escalated_delta_export_json,
    run_escalated_delta_export_filename_slug,
)

from nimbusware_console.run_escalated.captions import (
    run_escalated_operator_metrics_caption,
    run_escalated_occurred_at_caption,
    run_escalated_event_id_caption,
    run_escalated_reason_summary_caption,
    run_escalated_notes_preview_caption,
    run_escalated_actor_without_notes_caption,
    run_escalated_policy_cross_ref_caption,
    run_escalated_history_entry_count_caption,
    run_escalated_history_distinct_actors_caption,
    run_escalated_history_operator_metrics_caption,
    run_escalated_delta_transition_caption,
    run_escalated_delta_operator_metrics_caption,
)

from nimbusware_console.run_escalated.metrics import (
    run_escalated_operator_metrics,
    run_escalated_operator_metrics_table_rows,
    run_escalated_operator_metrics_caption,
    run_escalated_operator_metrics_export_json,
    run_escalated_operator_metrics_table_rows_csv,
    run_escalated_operator_metrics_export_filename_slug,
    run_escalated_history_operator_metrics,
    run_escalated_history_operator_metrics_table_rows,
    run_escalated_history_operator_metrics_caption,
    run_escalated_history_operator_metrics_export_json,
    run_escalated_history_operator_metrics_table_rows_csv,
    run_escalated_history_operator_metrics_export_filename_slug,
    run_escalated_delta_operator_metrics,
    run_escalated_delta_operator_metrics_table_rows,
    run_escalated_delta_operator_metrics_caption,
    run_escalated_delta_operator_metrics_export_json,
    run_escalated_delta_operator_metrics_table_rows_csv,
    run_escalated_delta_operator_metrics_export_filename_slug,
)

__all__ = [
    "run_escalated_actor_without_notes_caption",
    "run_escalated_delta_export_filename_slug",
    "run_escalated_delta_export_json",
    "run_escalated_delta_from_timeline",
    "run_escalated_delta_operator_metrics",
    "run_escalated_delta_operator_metrics_caption",
    "run_escalated_delta_operator_metrics_export_filename_slug",
    "run_escalated_delta_operator_metrics_export_json",
    "run_escalated_delta_operator_metrics_table_rows",
    "run_escalated_delta_operator_metrics_table_rows_csv",
    "run_escalated_delta_summary_rows",
    "run_escalated_delta_table_rows_csv",
    "run_escalated_delta_transition_caption",
    "run_escalated_event_id_caption",
    "run_escalated_export_filename_slug",
    "run_escalated_export_json",
    "run_escalated_from_timeline",
    "run_escalated_history_distinct_actors_caption",
    "run_escalated_history_entry_count_caption",
    "run_escalated_history_export_filename_slug",
    "run_escalated_history_export_json",
    "run_escalated_history_from_timeline",
    "run_escalated_history_operator_metrics",
    "run_escalated_history_operator_metrics_caption",
    "run_escalated_history_operator_metrics_export_filename_slug",
    "run_escalated_history_operator_metrics_export_json",
    "run_escalated_history_operator_metrics_table_rows",
    "run_escalated_history_operator_metrics_table_rows_csv",
    "run_escalated_history_table_rows",
    "run_escalated_history_table_rows_csv",
    "run_escalated_notes_preview_caption",
    "run_escalated_occurred_at_caption",
    "run_escalated_operator_metrics",
    "run_escalated_operator_metrics_caption",
    "run_escalated_operator_metrics_export_filename_slug",
    "run_escalated_operator_metrics_export_json",
    "run_escalated_operator_metrics_table_rows",
    "run_escalated_operator_metrics_table_rows_csv",
    "run_escalated_policy_cross_ref_caption",
    "run_escalated_reason_summary_caption",
    "run_escalated_summary_rows",
    "run_escalated_summary_rows_csv",
]
