from __future__ import annotations

from nimbusware_env.settings_catalog import (
    SettingDef,
    SettingKind,
    SettingScope,
)

_BOOL = SettingKind.BOOL
_INT = SettingKind.INT
_STR = SettingKind.STR
_ENUM = SettingKind.ENUM
_INSTALL = SettingScope.INSTALL
_SYSTEM = SettingScope.SYSTEM
_USER = SettingScope.USER
_INTERNAL = SettingScope.INTERNAL


def _uc(key: str, label: str) -> SettingDef:
    return SettingDef(
        key,
        _SYSTEM,
        _BOOL,
        "",
        label,
        "Empty = follow workflow YAML; set to force on/off.",
        "System — universal critique overrides",
    )


def _internal(
    key: str,
    label: str,
    *,
    kind: SettingKind = _STR,
    default: str = "",
    choices: tuple[str, ...] = (),
) -> SettingDef:
    return SettingDef(
        key,
        _INTERNAL,
        kind,
        default,
        label,
        "CI/dev/test only; not stored in Postgres.",
        "Internal — CI and dev",
        choices=choices,
        admin_editable=False,
        user_editable=False,
    )


def _install(
    key: str,
    label: str,
    *,
    kind: SettingKind = _STR,
    default: str = "",
    choices: tuple[str, ...] = (),
) -> SettingDef:
    return SettingDef(
        key,
        _INSTALL,
        kind,
        default,
        label,
        "Install / infrastructure (.env only).",
        "Install — infrastructure",
        choices=choices,
        admin_editable=False,
        user_editable=False,
    )


def extended_defs() -> tuple[SettingDef, ...]:
    uc_keys: tuple[tuple[str, str], ...] = (
        ("NIMBUSWARE_IMPLEMENTATION_CRITIQUE_LLM", "Implementation critique LLM"),
        ("NIMBUSWARE_ENABLE_TEST_WRITER_CRITIQUE", "Enable test writer critique"),
        ("NIMBUSWARE_TEST_WRITER_CRITIQUE_LLM", "Test writer critique LLM"),
        ("NIMBUSWARE_STUB_TEST_WRITER_CRITICS", "Stub test writer critics"),
        ("NIMBUSWARE_ENABLE_PLANNER_CRITIQUE", "Enable planner critique"),
        ("NIMBUSWARE_PLANNER_CRITIQUE_LLM", "Planner critique LLM"),
        ("NIMBUSWARE_STUB_PLANNER_CRITICS", "Stub planner critics"),
        ("NIMBUSWARE_ENABLE_FRONTEND_WRITER_CRITIQUE", "Enable frontend writer critique"),
        ("NIMBUSWARE_FRONTEND_WRITER_CRITIQUE_LLM", "Frontend writer critique LLM"),
        ("NIMBUSWARE_STUB_FRONTEND_WRITER_CRITICS", "Stub frontend writer critics"),
        ("NIMBUSWARE_ENABLE_MODULE_INTEGRATOR_CRITIQUE", "Enable module integrator critique"),
        ("NIMBUSWARE_MODULE_INTEGRATOR_CRITIQUE_LLM", "Module integrator critique LLM"),
        ("NIMBUSWARE_STUB_MODULE_INTEGRATOR_CRITICS", "Stub module integrator critics"),
        (
            "NIMBUSWARE_UNIVERSAL_CRITIQUE_STAGE_FAILED_ON_GATE_FAIL",
            "UC stage failed on gate fail (all panels)",
        ),
        (
            "NIMBUSWARE_UNIVERSAL_CRITIQUE_EMIT_FINDING_ON_GATE_FAIL",
            "UC emit finding on gate fail (all panels)",
        ),
        (
            "NIMBUSWARE_UNIVERSAL_CRITIQUE_HARD_BLOCK_ON_GATE_FAIL",
            "UC hard block on gate fail (all panels)",
        ),
    )
    uc = tuple(_uc(k, label) for k, label in uc_keys)

    install = (
        _install("NIMBUSWARE_API_HOST", "API bind host", default="0.0.0.0"),
        _install(
            "NIMBUSWARE_UI",
            "Desktop UI mode",
            kind=_ENUM,
            default="maker",
            choices=("maker", "admin", "console"),
        ),
        _install("NIMBUSWARE_API_PORT", "API port override"),
        _install("NIMBUSWARE_MAKER_URL", "Maker URL", default="http://127.0.0.1:8501"),
        _install(
            "NIMBUSWARE_ADMIN_CONSOLE_URL", "Admin console URL", default="http://127.0.0.1:8502"
        ),
        _install("NIMBUSWARE_CONFIG_FROM_FILES", "Config from files only", kind=_BOOL, default="0"),
        _install("NIMBUSWARE_CONFIG_NOTIFY", "Config NOTIFY pub/sub", kind=_BOOL, default="0"),
        _install(
            "NIMBUSWARE_ROLES_FROM_DB", "Roles registry from Postgres", kind=_BOOL, default="0"
        ),
        _install("NIMBUSWARE_FLEET_MEMORY_STORE_URI", "Fleet memory store URI"),
        _install("NIMBUSWARE_FLEET_MEMORY_STORE_DIR", "Fleet memory store directory"),
        _install("OLLAMA_HOST", "Ollama API URL", default="http://127.0.0.1:11434"),
        _install("NIMBUSWARE_POSTGRES_SUPERPASSWORD", "Postgres superuser password"),
        _install("NIMBUSWARE_SCRAPER_ARTIFACT_OBJECT_STORE_URL", "Scraper object store URL"),
        _install("NIMBUSWARE_SCRAPER_ARTIFACT_OBJECT_STORE_BUCKET", "Scraper object store bucket"),
        _install(
            "NIMBUSWARE_SCRAPER_ARTIFACT_OBJECT_STORE_PRIMARY",
            "Object store primary",
            kind=_BOOL,
            default="0",
        ),
        _install(
            "NIMBUSWARE_SCRAPER_ARTIFACT_LOCAL_MIRROR",
            "Mirror object-store scraper artifacts locally",
            kind=_BOOL,
            default="0",
        ),
        _install(
            "NIMBUSWARE_SCRAPER_ARTIFACT_OBJECT_STORE_TIMEOUT_SECONDS",
            "Object store request timeout seconds",
            kind=_INT,
            default="30",
        ),
        _install(
            "NIMBUSWARE_SCRAPER_ARTIFACT_OBJECT_STORE_DELETE_MAX_ATTEMPTS",
            "Max delete attempts for object-store prune",
            kind=_INT,
            default="1",
        ),
        _install(
            "NIMBUSWARE_HW_EXPECT_MIN_TIER",
            "Expected minimum hardware tier for fleet aggregate",
            kind=_STR,
            default="",
            choices=("", "weak", "standard", "strong"),
        ),
        _install("NIMBUSWARE_TENANT_ID", "Enterprise tenant id"),
        _install("NIMBUSWARE_MAKER_STATE_DIR", "Maker session state directory"),
        _install("NIMBUSWARE_OLLAMA_BASE_URL", "Ollama base URL override"),
        _install("NIMBUSWARE_HW_SSH_HOST", "Enterprise SSH hardware probe host"),
        _install("NIMBUSWARE_HW_SSH_IDENTITY", "SSH private key path for hardware probe"),
        _install(
            "NIMBUSWARE_HW_FLEET_HOSTS",
            "Comma-separated SSH hosts for fleet hardware tier aggregate",
        ),
        _install("NIMBUSWARE_WEBHOOK_SECRET", "External chat webhook HMAC secret"),
        _install("NIMBUSWARE_SANDBOX_K8S_EXEC_POD", "Fleet sandbox pod for kubectl exec"),
        _install("NIMBUSWARE_SANDBOX_K8S_NAMESPACE", "Fleet sandbox Kubernetes namespace"),
        _install("NIMBUSWARE_SANDBOX_K8S_WORKDIR", "Working directory inside fleet sandbox pod"),
        _install("NIMBUSWARE_E2B_API_KEY", "Enterprise E2B fleet sandbox API key"),
        _install("NIMBUSWARE_E2B_TEMPLATE", "Optional E2B sandbox template id"),
    )

    system_extra = (
        SettingDef(
            "NIMBUSWARE_PREFLIGHT_JSON_PROBE",
            _SYSTEM,
            _BOOL,
            "0",
            "Preflight JSON probe",
            "Extra JSON probe during Ollama preflight.",
            "System — runtime",
        ),
        SettingDef(
            "NIMBUSWARE_PREFLIGHT_LATENCY_SAMPLES",
            _SYSTEM,
            _INT,
            "1",
            "Preflight latency samples",
            "Sample count for preflight latency (1–20).",
            "System — runtime",
        ),
        SettingDef(
            "NIMBUSWARE_RUN_MYPY",
            _SYSTEM,
            _BOOL,
            "0",
            "Run mypy on verify",
            "Type-check changed paths during verify.",
            "System — verifiers",
        ),
        SettingDef(
            "NIMBUSWARE_SEMGREP_CONFIG",
            _SYSTEM,
            _STR,
            "p/ci",
            "Semgrep config",
            "Semgrep ruleset for verify scan.",
            "System — verifiers",
        ),
        SettingDef(
            "NIMBUSWARE_AGENT_EVALUATOR_AUTO_PROMOTE",
            _SYSTEM,
            _BOOL,
            "0",
            "Agent evaluator auto-promote",
            "Auto-promote agent evaluator findings.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_AGENT_EVALUATOR_AUTO_CREATE",
            _SYSTEM,
            _BOOL,
            "0",
            "Agent evaluator auto-create",
            "Auto-create agent evaluator artifacts.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_AGENT_EVALUATOR_LLM_STUB",
            _SYSTEM,
            _BOOL,
            "0",
            "Agent evaluator LLM stub",
            "Stub LLM for agent evaluator stage.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_PROBATION_AUTO_SHELVE",
            _SYSTEM,
            _BOOL,
            "1",
            "Probation auto-shelve",
            "Auto-shelve personas when probation reliability thresholds fail.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_PROBATION_NOTIFY_BEFORE_PROMOTE",
            _SYSTEM,
            _BOOL,
            "1",
            "Probation promote notice",
            "Emit a finding before auto-promoting probation personas.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_FAST_SLICE",
            _SYSTEM,
            _BOOL,
            "",
            "Fast slice",
            "Empty = workflow YAML; skip optional critic matrix below HIGH severity.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_PERSONA_COVERAGE_CRITIQUE",
            _SYSTEM,
            _BOOL,
            "",
            "Persona coverage critique",
            "Empty = YAML; force persona coverage critique.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_PERSONA_COVERAGE_CRITIQUE_LLM",
            _SYSTEM,
            _BOOL,
            "",
            "Persona coverage critique LLM",
            "Empty = YAML; LLM for persona coverage critique.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_SELF_REFINEMENT_UNGATED_LOOP",
            _SYSTEM,
            _BOOL,
            "",
            "Self-refinement ungated loop",
            "Empty = YAML; ungated self-refinement loop.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_SELF_REFINEMENT_AUTO_PROMOTE",
            _SYSTEM,
            _BOOL,
            "0",
            "Self-refinement auto-promote",
            "Auto-promote self-refinement findings.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_SELF_REFINEMENT_CRITIQUE_STUB",
            _SYSTEM,
            _BOOL,
            "",
            "Self-refinement critique stub",
            "Empty = YAML; stub self-refinement critique.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_INTEGRATION_ADAPTER_WRITER",
            _SYSTEM,
            _BOOL,
            "",
            "Integration adapter writer",
            "Empty = YAML; integration adapter writer stage.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_NETWORK_RESILIENCE_CRITIQUE",
            _SYSTEM,
            _BOOL,
            "",
            "Network resilience critique",
            "Empty = YAML; network resilience critique panel.",
            "System — critics",
        ),
        SettingDef(
            "NIMBUSWARE_NETWORK_RESILIENCE_CRITIQUE_LLM",
            _SYSTEM,
            _BOOL,
            "",
            "Network resilience critique LLM",
            "Empty = YAML; LLM for network resilience critique.",
            "System — critics",
        ),
        SettingDef(
            "NIMBUSWARE_PERFORMANCE_CRITIQUE",
            _SYSTEM,
            _BOOL,
            "",
            "Performance critique",
            "Empty = YAML; performance critique panel.",
            "System — critics",
        ),
        SettingDef(
            "NIMBUSWARE_PERFORMANCE_CRITIQUE_LLM",
            _SYSTEM,
            _BOOL,
            "",
            "Performance critique LLM",
            "Empty = YAML; LLM for performance critique.",
            "System — critics",
        ),
        SettingDef(
            "NIMBUSWARE_SECURITY_CRITIQUE",
            _SYSTEM,
            _BOOL,
            "",
            "Security critique",
            "Empty = YAML; security critique panel.",
            "System — critics",
        ),
        SettingDef(
            "NIMBUSWARE_SECURITY_CRITIQUE_LLM",
            _SYSTEM,
            _BOOL,
            "",
            "Security critique LLM",
            "Empty = YAML; LLM for security critique.",
            "System — critics",
        ),
        SettingDef(
            "NIMBUSWARE_TEST_WRITER_STAGE",
            _SYSTEM,
            _BOOL,
            "",
            "Test writer stage",
            "Tri-state override for test writer stage.",
            "System — pipeline",
        ),
        SettingDef(
            "NIMBUSWARE_TEST_WRITER_LLM_BODY",
            _SYSTEM,
            _BOOL,
            "",
            "Test writer LLM body",
            "Tri-state override for test writer LLM body.",
            "System — pipeline",
        ),
        SettingDef(
            "NIMBUSWARE_TEST_WRITER_LLM_STUB",
            _SYSTEM,
            _BOOL,
            "",
            "Test writer LLM stub",
            "Tri-state override for test writer LLM stub.",
            "System — pipeline",
        ),
        SettingDef(
            "NIMBUSWARE_BUNDLE_MEMORY_RANK_WEIGHT",
            _SYSTEM,
            _STR,
            "0.2",
            "Bundle memory rank weight",
            "Weight for bundle memory ranking.",
            "System — memory",
        ),
        SettingDef(
            "NIMBUSWARE_MEMORY_EMBEDDING_MODEL",
            _SYSTEM,
            _STR,
            "",
            "Memory embedding model",
            "Override embedding model for memory index.",
            "System — memory",
        ),
        SettingDef(
            "NIMBUSWARE_SCRAPER_ARTIFACT_MAX_AGE_DAYS",
            _SYSTEM,
            _INT,
            "",
            "Scraper artifact max age days",
            "Retention max age for scraper artifacts.",
            "System — egress",
        ),
        SettingDef(
            "NIMBUSWARE_FLEET_OLLAMA_SLI_SAMPLES",
            _SYSTEM,
            _INT,
            "60",
            "Fleet Ollama SLI samples",
            "Sample count for fleet Ollama SLI CLI.",
            "System — fleet",
        ),
        SettingDef(
            "NIMBUSWARE_FLEET_OLLAMA_SLI_INTERVAL_SEC",
            _SYSTEM,
            _INT,
            "5",
            "Fleet Ollama SLI interval sec",
            "Interval between fleet Ollama SLI samples.",
            "System — fleet",
        ),
        SettingDef(
            "NIMBUSWARE_FLEET_QUEUE_BACKPRESSURE_DEPTH",
            _SYSTEM,
            _INT,
            "100",
            "Fleet queue pending depth cap",
            "Pause verify dispatch when Redis pending depth exceeds cap.",
            "System — fleet",
        ),
        SettingDef(
            "NIMBUSWARE_FLEET_QUEUE_BACKPRESSURE_IN_FLIGHT",
            _SYSTEM,
            _INT,
            "20",
            "Fleet queue in-flight cap",
            "Pause verify dispatch when in-flight tasks exceed cap.",
            "System — fleet",
        ),
        SettingDef(
            "NIMBUSWARE_SCRAPER_ARTIFACT_OBJECT_STORE_PRUNE",
            _SYSTEM,
            _BOOL,
            "0",
            "Prune scraper artifacts from object store",
            "Enable retention prune against object-store primary backend.",
            "System — scraper",
        ),
    )

    user_extra = (
        SettingDef(
            "NIMBUSWARE_SLICE_P3_EVIDENCE",
            _USER,
            _BOOL,
            "1",
            "Slice P3 evidence",
            "Emit P3 evidence stages during slice implement.",
            "User — maker runtime",
        ),
        SettingDef(
            "NIMBUSWARE_SLICE_BRANCH_PREFIX",
            _USER,
            _STR,
            "nimbusware/run-",
            "Git branch prefix",
            "Prefix for auto-created git branches.",
            "User — git outputs",
        ),
        SettingDef(
            "NIMBUSWARE_SLICE_PACKET_MAX_CHARS",
            _USER,
            _INT,
            "",
            "Slice packet max chars",
            "Legacy override; prefer NIMBUSWARE_SLICE_BUDGET_PRESET. Applies only when explicitly set.",
            "User — maker runtime",
        ),
        SettingDef(
            "NIMBUSWARE_SLICE_REPO_MAP_ENABLED",
            _USER,
            _BOOL,
            "1",
            "Slice repo map enabled",
            "Inject repo tree + import graph into slice context packets.",
            "User — maker runtime",
        ),
        SettingDef(
            "NIMBUSWARE_SLICE_REPO_MAP_MAX_CHARS",
            _USER,
            _INT,
            "",
            "Slice repo map max chars",
            "Legacy override; prefer NIMBUSWARE_SLICE_BUDGET_PRESET. Applies only when explicitly set.",
            "User — maker runtime",
        ),
        SettingDef(
            "NIMBUSWARE_SLICE_LSP_ENABLED",
            _USER,
            _BOOL,
            "1",
            "Slice Pyright LSP symbols",
            "When enabled, try pyright-langserver documentSymbol before AST symbol sketch.",
            "User — maker runtime",
        ),
        SettingDef(
            "NIMBUSWARE_SLICE_LSP_COMMAND",
            _USER,
            _STR,
            "",
            "Slice LSP command",
            "Override langserver argv (e.g. pyright-langserver or npx pyright-langserver).",
            "User — maker runtime",
        ),
        SettingDef(
            "NIMBUSWARE_SLICE_LSP_TIMEOUT_SEC",
            _USER,
            _INT,
            "8",
            "Slice LSP timeout (sec)",
            "Per-request timeout; hung servers fall back to AST sketch.",
            "User — maker runtime",
        ),
        SettingDef(
            "NIMBUSWARE_SLICE_SYMBOL_SKETCH_MAX_CHARS",
            _USER,
            _INT,
            "",
            "Symbol sketch max chars",
            "Legacy override; prefer NIMBUSWARE_SLICE_BUDGET_PRESET. Applies only when explicitly set.",
            "User — maker runtime",
        ),
        SettingDef(
            "NIMBUSWARE_LLM_HISTORY_MAX_CHARS",
            _USER,
            _INT,
            "",
            "LLM history max chars",
            "Legacy override; prefer NIMBUSWARE_SLICE_BUDGET_PRESET. Applies only when explicitly set.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_READ_MAX_CHARS",
            _USER,
            _INT,
            "16000",
            "Read tool max chars",
            "Max characters returned by the agent read tool.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_SHELL_OUTPUT_MAX_CHARS",
            _USER,
            _INT,
            "4000",
            "Shell output max chars",
            "Max characters of shell command output in agent tool results.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_AGENT_JIT_LOOP",
            _USER,
            _BOOL,
            "1",
            "Agent JIT tool loop",
            "Multi-turn tool loop for slice implement agent mode (vs single-shot plan).",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_AGENT_TOOLS",
            _USER,
            _STR,
            "read,write,edit,grep,shell",
            "Agent tool allowlist",
            "Comma-separated tools exposed to slice implement agent (optional: find, ls).",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_PROJECTION_PRUNE_AGENT_TOOLS",
            _USER,
            _BOOL,
            "1",
            "Prune agent tool outputs in projections",
            "Replace stale agent tool log lines in theater/timeline with pruned placeholders.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_HANDOFF_MAX_CHARS",
            _USER,
            _INT,
            "",
            "Handoff summary max chars",
            "Legacy override; prefer NIMBUSWARE_SLICE_BUDGET_PRESET. Applies only when explicitly set.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_HANDOFF_LLM_SUMMARY",
            _USER,
            _BOOL,
            "0",
            "Handoff LLM summary",
            "When enabled, optionally refine handoff text via LLM (default deterministic).",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_CAMPAIGN_COMPACT_ENABLED",
            _USER,
            _BOOL,
            "1",
            "Campaign compaction",
            "Summarize older slice handoffs to bound planner context in long runs.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_AGENT_COMPACT",
            _USER,
            _BOOL,
            "1",
            "Manual run compaction",
            "Allow POST /v1/runs/{id}/compact and MCP nimbusware_compact_run.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_CAMPAIGN_KEEP_RECENT_TOKENS",
            _USER,
            _INT,
            "12000",
            "Campaign keep recent tokens",
            "Verbatim recent handoff token budget; defaults from hardware profile when unset.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_CAMPAIGN_RESERVE_TOKENS",
            _USER,
            _INT,
            "8000",
            "Campaign reserve tokens",
            "Output reservation subtracted from keep-recent window.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_MEMORY_RETRIEVAL_K",
            _USER,
            _INT,
            "5",
            "Memory retrieval top-k",
            "Max memory chunks injected per slice (workflow YAML may override).",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_MEMORY_EXCERPT_MAX_CHARS",
            _USER,
            _INT,
            "",
            "Memory excerpt max chars",
            "Legacy override; prefer NIMBUSWARE_SLICE_BUDGET_PRESET. Applies only when explicitly set.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_CONTEXT_ARTIFACT_FAISS_REBUILD",
            _USER,
            _BOOL,
            "0",
            "Rebuild FAISS after context-artifact bridge",
            "Rebuild memory FAISS index after context-artifact bridge-memory.",
            "User — context efficiency",
        ),
        SettingDef(
            "NIMBUSWARE_AXE_ENABLED",
            _USER,
            _BOOL,
            "0",
            "Axe-core in human-fidelity suite",
            "Run axe-core accessibility rule packs during human-fidelity checks.",
            "User — maker runtime",
        ),
        SettingDef(
            "NIMBUSWARE_SWE_BENCH_ENABLED",
            _USER,
            _BOOL,
            "1",
            "SWE-bench harness enabled",
            "When off, swe_bench_harness.py exits 0 without running.",
            "User — benchmarks",
        ),
        SettingDef(
            "NIMBUSWARE_SWE_BENCH_MANIFEST",
            _USER,
            _STR,
            "",
            "SWE-bench manifest path",
            "Path to swe_bench manifest JSON (default: tests/fixtures/swe_bench/manifest.json).",
            "User — benchmarks",
        ),
        SettingDef(
            "NIMBUSWARE_MAX_PARALLEL_WRITERS",
            _USER,
            _INT,
            "",
            "Max parallel writers",
            "Override hardware governor parallel writer cap.",
            "User — hardware governor",
        ),
        SettingDef(
            "NIMBUSWARE_ALLOW_PARALLEL_CRITICS",
            _USER,
            _BOOL,
            "0",
            "Allow parallel critics",
            "Allow critics to run in parallel under governor.",
            "User — hardware governor",
        ),
        SettingDef(
            "NIMBUSWARE_RESERVE_RAM_GB",
            _USER,
            _INT,
            "2",
            "Reserve RAM GB",
            "RAM reserved for OS outside governor cap.",
            "User — hardware governor",
        ),
        SettingDef(
            "NIMBUSWARE_WORKFLOW_PROFILE",
            _USER,
            _STR,
            "",
            "Workflow profile (legacy alias)",
            "Legacy alias for NIMBUSWARE_DEFAULT_WORKFLOW_PROFILE.",
            "User — maker runtime",
        ),
        SettingDef(
            "NIMBUSWARE_SLICE_REPLAN_MAX",
            _USER,
            _INT,
            "",
            "Slice replan max attempts",
            "Max replan attempts per slice.",
            "User — maker runtime",
        ),
        SettingDef(
            "NIMBUSWARE_SLICE_STUB_LOC_PER_FILE",
            _USER,
            _INT,
            "",
            "Slice stub LOC per file",
            "Stub implement LOC budget per file.",
            "User — maker runtime",
        ),
    )

    internal = (
        _internal("NIMBUSWARE_WORKSPACE", "Dev workspace path override"),
        _internal("NIMBUSWARE_REFACTOR_FORCE_FAIL", "Force refactor stage fail", kind=_BOOL),
        _internal("NIMBUSWARE_REFACTOR_STAGE", "Refactor stage override"),
        _internal(
            "NIMBUSWARE_PARALLEL_WRITER_TEST_DELAY_SECONDS", "Parallel writer test delay", kind=_INT
        ),
        _internal(
            "NIMBUSWARE_HW_FIXTURE",
            "Hardware profile fixture",
            kind=_ENUM,
            choices=("weak", "medium", "strong"),
        ),
        _internal("NIMBUSWARE_HW_SSH_MOCK", "Mock SSH hardware probe", kind=_BOOL),
        _internal(
            "NIMBUSWARE_PRESSURE_DEGRADE_STUB", "Degrade LLM to stub under RAM block", kind=_BOOL
        ),
        _internal("NIMBUSWARE_CI_GITHUB_REPO", "CI GitHub repo slug"),
        _internal("NIMBUSWARE_CI_HEAD_SHA", "CI head SHA"),
        _internal("NIMBUSWARE_GITLAB_TOKEN", "GitLab API token for external CI"),
        _internal("NIMBUSWARE_CI_GITLAB_PROJECT", "GitLab project id or namespace/project"),
        _internal("NIMBUSWARE_GITLAB_API_BASE", "GitLab API base URL"),
        _internal("NIMBUSWARE_TIMELINE_BASE_URL", "Timeline base URL for CI"),
        _internal("NIMBUSWARE_FLEET_OLLAMA_SLI_BASE_URL", "Fleet Ollama SLI base URL"),
        _internal("NIMBUSWARE_FLEET_OLLAMA_SLI_EXPORT_PATH", "Fleet Ollama SLI export path"),
        _internal("NIMBUSWARE_FLEET_OLLAMA_SLI_HEALTH_PATH", "Fleet Ollama SLI health path"),
        _internal("NIMBUSWARE_WORKSPACE_SNAPSHOT_DIR", "Workspace snapshot directory"),
        _internal("NIMBUSWARE_MEMORY_INDEX_DIR", "Memory index directory"),
        _internal("NIMBUSWARE_SCRAPER_ARTIFACT_DIR", "Scraper artifact directory"),
        _internal("NIMBUSWARE_PRUNE_STATUS_PATH", "Prune status export path"),
        _internal("NIMBUSWARE_SQL_QUERY_COUNT_MAX", "SQL query count max", kind=_INT),
        _internal("NIMBUSWARE_TEST_SQL_QUERY_COUNT", "Test SQL query count flag", kind=_BOOL),
        _internal("NIMBUSWARE_TEST_WRITER_STAGE_CMD", "Test writer stage command override"),
        _internal("NIMBUSWARE_QUICK_MODE", "Quick mode bootstrap", kind=_BOOL),
        _internal(
            "NIMBUSWARE_FACTORY_EXPLORATORY_CRAWL",
            "Enable exploratory Playwright ISM crawl on factory T3",
            kind=_BOOL,
        ),
        _internal(
            "NIMBUSWARE_FACTORY_EXPLORATORY_MAX_CLICKS",
            "Max Playwright navigations during factory exploratory ISM crawl",
            kind=_INT,
        ),
        _internal(
            "NIMBUSWARE_FACTORY_EXPLORATORY_MAX_DEPTH",
            "Max link depth during factory exploratory ISM crawl",
            kind=_INT,
        ),
        _internal("NIMBUSWARE_PUT_SANDBOX", "PUT preview sandbox mode (docker)"),
        _internal(
            "NIMBUSWARE_DEV_ENV_ENABLED", "Enable persistent dev environment supervisor", kind=_BOOL
        ),
        _internal(
            "NIMBUSWARE_DEV_ENV_PORT_BASE", "Base port for dev env session allocation", kind=_INT
        ),
        _internal(
            "NIMBUSWARE_DEV_ENV_BASE_URL", "Attach to external dev server instead of spawning"
        ),
        _internal("NIMBUSWARE_PUT_BASE_URL", "External PUT preview base URL override"),
        _internal(
            "NIMBUSWARE_ALLOW_WORKFLOW_YAML_WRITE",
            "Allow integrator workflow YAML write from console",
            kind=_BOOL,
            default="0",
        ),
        _internal(
            "NIMBUSWARE_OIDC_MOCK",
            "Mock OIDC admin sign-in (dev only)",
            kind=_BOOL,
            default="0",
        ),
        _internal(
            "NIMBUSWARE_UI_CONTROLLER_ENABLED", "Enable UI controller regression", kind=_BOOL
        ),
        _internal(
            "NIMBUSWARE_LAUNCH_TEST_ENABLED",
            "Enable launch-test writer/critic stages on full-stack profiles",
            kind=_BOOL,
        ),
        _internal(
            "NIMBUSWARE_LAUNCH_TEST_STUB",
            "Stub unknown launch_test stages (tests only)",
            kind=_BOOL,
        ),
        _internal(
            "NIMBUSWARE_LAUNCH_TEST_WRITER_MODEL",
            "Ollama model for launch-test UI flow writer (empty = ISM synthesis only)",
            kind=_STR,
        ),
        _internal(
            "NIMBUSWARE_DEV_ENV_MILESTONES_BYPASS",
            "Skip M1–M6 gating for dev-env auto-start and regression",
            kind=_BOOL,
        ),
        _internal(
            "NIMBUSWARE_HUMAN_FIDELITY_ENABLED",
            "Run human-fidelity suite before slice gate when dev env is up",
            kind=_BOOL,
        ),
        _internal(
            "NIMBUSWARE_FACTORY_EVIDENCE_OBJECT_STORE_URL",
            "S3-compatible URL for factory evidence zip mirror",
        ),
        _internal(
            "NIMBUSWARE_FACTORY_EVIDENCE_OBJECT_STORE_BUCKET",
            "Bucket for factory evidence object store",
        ),
        _internal("NIMBUSWARE_MAKER_VAPID_PRIVATE_KEY", "Maker Web Push VAPID private key"),
        _internal("NIMBUSWARE_MAKER_VAPID_SUBJECT", "Maker Web Push VAPID subject (mailto:)"),
        _internal(
            "NIMBUSWARE_MAKER_PUSH_SUBSCRIPTIONS_FILE",
            "Path to persisted push subscription JSON",
        ),
        _internal("NIMBUSWARE_FLEET_PLAYWRIGHT_WS_ENDPOINT", "Fleet Playwright WS endpoint"),
        _internal("NIMBUSWARE_MAKER_VAPID_PUBLIC_KEY", "Maker Web Push VAPID public key"),
        _internal("NIMBUSWARE_DATA_DIR", "Nimbusware data directory root"),
    )

    return uc + install + system_extra + user_extra + internal
