"""Extended catalog entries (UC overrides, install, internal)."""

from __future__ import annotations

from nimbusware_env.settings_catalog import (
    SettingDef,
    SettingKind,
    SettingScope,
)

_BOOL = SettingKind.BOOL
_INT = SettingKind.INT
_STR = SettingKind.STR
_ENUM = SettingKind.ENUM
_INSTALL = SettingScope.INSTALL
_SYSTEM = SettingScope.SYSTEM
_USER = SettingScope.USER
_INTERNAL = SettingScope.INTERNAL


def _uc(key: str, label: str) -> SettingDef:
    return SettingDef(
        key,
        _SYSTEM,
        _BOOL,
        "",
        label,
        "Empty = follow workflow YAML; set to force on/off.",
        "System — universal critique overrides",
    )


def _internal(
    key: str,
    label: str,
    *,
    kind: SettingKind = _STR,
    default: str = "",
    choices: tuple[str, ...] = (),
) -> SettingDef:
    return SettingDef(
        key,
        _INTERNAL,
        kind,
        default,
        label,
        "CI/dev/test only; not stored in Postgres.",
        "Internal — CI and dev",
        choices=choices,
        admin_editable=False,
        user_editable=False,
    )


def _install(
    key: str,
    label: str,
    *,
    kind: SettingKind = _STR,
    default: str = "",
    choices: tuple[str, ...] = (),
) -> SettingDef:
    return SettingDef(
        key,
        _INSTALL,
        kind,
        default,
        label,
        "Install / infrastructure (.env only).",
        "Install — infrastructure",
        choices=choices,
        admin_editable=False,
        user_editable=False,
    )


def extended_defs() -> tuple[SettingDef, ...]:
    uc_keys: tuple[tuple[str, str], ...] = (
        ("HERMES_IMPLEMENTATION_CRITIQUE_LLM", "Implementation critique LLM"),
        (
            "HERMES_IMPLEMENTATION_CRITIQUE_STAGE_FAILED_ON_GATE_FAIL",
            "Impl stage failed on gate fail",
        ),
        (
            "HERMES_IMPLEMENTATION_CRITIQUE_EMIT_FINDING_ON_GATE_FAIL",
            "Impl emit finding on gate fail",
        ),
        ("HERMES_IMPLEMENTATION_CRITIQUE_HARD_BLOCK_ON_GATE_FAIL", "Impl hard block on gate fail"),
        ("HERMES_ENABLE_TEST_WRITER_CRITIQUE", "Enable test writer critique"),
        ("HERMES_TEST_WRITER_CRITIQUE_LLM", "Test writer critique LLM"),
        ("HERMES_STUB_TEST_WRITER_CRITICS", "Stub test writer critics"),
        ("HERMES_TEST_WRITER_CRITIQUE_STAGE_FAILED_ON_GATE_FAIL", "TW stage failed on gate fail"),
        ("HERMES_TEST_WRITER_CRITIQUE_EMIT_FINDING_ON_GATE_FAIL", "TW emit finding on gate fail"),
        ("HERMES_TEST_WRITER_CRITIQUE_HARD_BLOCK_ON_GATE_FAIL", "TW hard block on gate fail"),
        ("HERMES_ENABLE_PLANNER_CRITIQUE", "Enable planner critique"),
        ("HERMES_PLANNER_CRITIQUE_LLM", "Planner critique LLM"),
        ("HERMES_STUB_PLANNER_CRITICS", "Stub planner critics"),
        ("HERMES_PLANNER_CRITIQUE_STAGE_FAILED_ON_GATE_FAIL", "Planner stage failed on gate fail"),
        ("HERMES_PLANNER_CRITIQUE_EMIT_FINDING_ON_GATE_FAIL", "Planner emit finding on gate fail"),
        ("HERMES_PLANNER_CRITIQUE_HARD_BLOCK_ON_GATE_FAIL", "Planner hard block on gate fail"),
        ("HERMES_ENABLE_FRONTEND_WRITER_CRITIQUE", "Enable frontend writer critique"),
        ("HERMES_FRONTEND_WRITER_CRITIQUE_LLM", "Frontend writer critique LLM"),
        ("HERMES_STUB_FRONTEND_WRITER_CRITICS", "Stub frontend writer critics"),
        (
            "HERMES_FRONTEND_WRITER_CRITIQUE_STAGE_FAILED_ON_GATE_FAIL",
            "FW stage failed on gate fail",
        ),
        (
            "HERMES_FRONTEND_WRITER_CRITIQUE_EMIT_FINDING_ON_GATE_FAIL",
            "FW emit finding on gate fail",
        ),
        ("HERMES_FRONTEND_WRITER_CRITIQUE_HARD_BLOCK_ON_GATE_FAIL", "FW hard block on gate fail"),
        ("HERMES_ENABLE_MODULE_INTEGRATOR_CRITIQUE", "Enable module integrator critique"),
        ("HERMES_MODULE_INTEGRATOR_CRITIQUE_LLM", "Module integrator critique LLM"),
        ("HERMES_STUB_MODULE_INTEGRATOR_CRITICS", "Stub module integrator critics"),
        (
            "HERMES_MODULE_INTEGRATOR_CRITIQUE_STAGE_FAILED_ON_GATE_FAIL",
            "MI stage failed on gate fail",
        ),
        (
            "HERMES_MODULE_INTEGRATOR_CRITIQUE_EMIT_FINDING_ON_GATE_FAIL",
            "MI emit finding on gate fail",
        ),
        ("HERMES_MODULE_INTEGRATOR_CRITIQUE_HARD_BLOCK_ON_GATE_FAIL", "MI hard block on gate fail"),
    )
    uc = tuple(_uc(k, label) for k, label in uc_keys)

    install = (
        _install("NIMBUSWARE_API_HOST", "API bind host", default="0.0.0.0"),
        _install("HERMES_API_HOST", "Legacy API bind host"),
        _install(
            "NIMBUSWARE_UI",
            "Desktop UI mode",
            kind=_ENUM,
            default="maker",
            choices=("maker", "admin", "console"),
        ),
        _install("NIMBUSWARE_API_PORT", "API port override"),
        _install("NIMBUSWARE_MAKER_URL", "Maker URL", default="http://127.0.0.1:8501"),
        _install(
            "NIMBUSWARE_ADMIN_CONSOLE_URL", "Admin console URL", default="http://127.0.0.1:8502"
        ),
        _install("NIMBUSWARE_CONFIG_FROM_FILES", "Config from files only", kind=_BOOL, default="0"),
        _install("NIMBUSWARE_CONFIG_NOTIFY", "Config NOTIFY pub/sub", kind=_BOOL, default="0"),
        _install(
            "NIMBUSWARE_ROLES_FROM_DB", "Roles registry from Postgres", kind=_BOOL, default="0"
        ),
        _install("NIMBUSWARE_FLEET_MEMORY_STORE_URI", "Fleet memory store URI"),
        _install("NIMBUSWARE_FLEET_MEMORY_STORE_DIR", "Fleet memory store directory"),
        _install("OLLAMA_HOST", "Ollama API URL", default="http://127.0.0.1:11434"),
        _install("NIMBUSWARE_POSTGRES_SUPERPASSWORD", "Postgres superuser password"),
        _install("HERMES_SCRAPER_ARTIFACT_OBJECT_STORE_URL", "Scraper object store URL"),
        _install("HERMES_SCRAPER_ARTIFACT_OBJECT_STORE_BUCKET", "Scraper object store bucket"),
        _install(
            "HERMES_SCRAPER_ARTIFACT_OBJECT_STORE_PRIMARY",
            "Object store primary",
            kind=_BOOL,
            default="0",
        ),
        _install("NIMBUSWARE_TENANT_ID", "Enterprise tenant id"),
        _install("NIMBUSWARE_MAKER_STATE_DIR", "Maker session state directory"),
        _install("HERMES_OLLAMA_BASE_URL", "Ollama base URL override"),
    )

    system_extra = (
        SettingDef(
            "HERMES_PREFLIGHT_JSON_PROBE",
            _SYSTEM,
            _BOOL,
            "0",
            "Preflight JSON probe",
            "Extra JSON probe during Ollama preflight.",
            "System — runtime",
        ),
        SettingDef(
            "HERMES_PREFLIGHT_LATENCY_SAMPLES",
            _SYSTEM,
            _INT,
            "1",
            "Preflight latency samples",
            "Sample count for preflight latency (1–20).",
            "System — runtime",
        ),
        SettingDef(
            "HERMES_RUN_MYPY",
            _SYSTEM,
            _BOOL,
            "0",
            "Run mypy on verify",
            "Type-check changed paths during verify.",
            "System — verifiers",
        ),
        SettingDef(
            "HERMES_SEMGREP_CONFIG",
            _SYSTEM,
            _STR,
            "p/ci",
            "Semgrep config",
            "Semgrep ruleset for verify scan.",
            "System — verifiers",
        ),
        SettingDef(
            "HERMES_AGENT_EVALUATOR_AUTO_PROMOTE",
            _SYSTEM,
            _BOOL,
            "0",
            "Agent evaluator auto-promote",
            "Auto-promote agent evaluator findings.",
            "System — optional stages",
        ),
        SettingDef(
            "HERMES_AGENT_EVALUATOR_AUTO_CREATE",
            _SYSTEM,
            _BOOL,
            "0",
            "Agent evaluator auto-create",
            "Auto-create agent evaluator artifacts.",
            "System — optional stages",
        ),
        SettingDef(
            "HERMES_AGENT_EVALUATOR_LLM_STUB",
            _SYSTEM,
            _BOOL,
            "0",
            "Agent evaluator LLM stub",
            "Stub LLM for agent evaluator stage.",
            "System — optional stages",
        ),
        SettingDef(
            "HERMES_PERSONA_COVERAGE_CRITIQUE",
            _SYSTEM,
            _BOOL,
            "",
            "Persona coverage critique",
            "Empty = YAML; force persona coverage critique.",
            "System — optional stages",
        ),
        SettingDef(
            "HERMES_PERSONA_COVERAGE_CRITIQUE_LLM",
            _SYSTEM,
            _BOOL,
            "",
            "Persona coverage critique LLM",
            "Empty = YAML; LLM for persona coverage critique.",
            "System — optional stages",
        ),
        SettingDef(
            "HERMES_SELF_REFINEMENT_UNGATED_LOOP",
            _SYSTEM,
            _BOOL,
            "",
            "Self-refinement ungated loop",
            "Empty = YAML; ungated self-refinement loop.",
            "System — optional stages",
        ),
        SettingDef(
            "HERMES_SELF_REFINEMENT_AUTO_PROMOTE",
            _SYSTEM,
            _BOOL,
            "0",
            "Self-refinement auto-promote",
            "Auto-promote self-refinement findings.",
            "System — optional stages",
        ),
        SettingDef(
            "HERMES_SELF_REFINEMENT_CRITIQUE_STUB",
            _SYSTEM,
            _BOOL,
            "",
            "Self-refinement critique stub",
            "Empty = YAML; stub self-refinement critique.",
            "System — optional stages",
        ),
        SettingDef(
            "HERMES_INTEGRATION_ADAPTER_WRITER",
            _SYSTEM,
            _BOOL,
            "",
            "Integration adapter writer",
            "Empty = YAML; integration adapter writer stage.",
            "System — optional stages",
        ),
        SettingDef(
            "HERMES_NETWORK_RESILIENCE_CRITIQUE",
            _SYSTEM,
            _BOOL,
            "",
            "Network resilience critique",
            "Empty = YAML; network resilience critique panel.",
            "System — critics",
        ),
        SettingDef(
            "HERMES_NETWORK_RESILIENCE_CRITIQUE_LLM",
            _SYSTEM,
            _BOOL,
            "",
            "Network resilience critique LLM",
            "Empty = YAML; LLM for network resilience critique.",
            "System — critics",
        ),
        SettingDef(
            "HERMES_PERFORMANCE_CRITIQUE",
            _SYSTEM,
            _BOOL,
            "",
            "Performance critique",
            "Empty = YAML; performance critique panel.",
            "System — critics",
        ),
        SettingDef(
            "HERMES_PERFORMANCE_CRITIQUE_LLM",
            _SYSTEM,
            _BOOL,
            "",
            "Performance critique LLM",
            "Empty = YAML; LLM for performance critique.",
            "System — critics",
        ),
        SettingDef(
            "HERMES_SECURITY_CRITIQUE",
            _SYSTEM,
            _BOOL,
            "",
            "Security critique",
            "Empty = YAML; security critique panel.",
            "System — critics",
        ),
        SettingDef(
            "HERMES_SECURITY_CRITIQUE_LLM",
            _SYSTEM,
            _BOOL,
            "",
            "Security critique LLM",
            "Empty = YAML; LLM for security critique.",
            "System — critics",
        ),
        SettingDef(
            "HERMES_TEST_WRITER_STAGE",
            _SYSTEM,
            _BOOL,
            "",
            "Test writer stage",
            "Tri-state override for test writer stage.",
            "System — pipeline",
        ),
        SettingDef(
            "HERMES_TEST_WRITER_LLM_BODY",
            _SYSTEM,
            _BOOL,
            "",
            "Test writer LLM body",
            "Tri-state override for test writer LLM body.",
            "System — pipeline",
        ),
        SettingDef(
            "HERMES_TEST_WRITER_LLM_STUB",
            _SYSTEM,
            _BOOL,
            "",
            "Test writer LLM stub",
            "Tri-state override for test writer LLM stub.",
            "System — pipeline",
        ),
        SettingDef(
            "HERMES_BUNDLE_MEMORY_RANK_WEIGHT",
            _SYSTEM,
            _STR,
            "0.2",
            "Bundle memory rank weight",
            "Weight for bundle memory ranking.",
            "System — memory",
        ),
        SettingDef(
            "HERMES_MEMORY_EMBEDDING_MODEL",
            _SYSTEM,
            _STR,
            "",
            "Memory embedding model",
            "Override embedding model for memory index.",
            "System — memory",
        ),
        SettingDef(
            "HERMES_SCRAPER_ARTIFACT_MAX_AGE_DAYS",
            _SYSTEM,
            _INT,
            "",
            "Scraper artifact max age days",
            "Retention max age for scraper artifacts.",
            "System — egress",
        ),
        SettingDef(
            "HERMES_FLEET_OLLAMA_SLI_SAMPLES",
            _SYSTEM,
            _INT,
            "60",
            "Fleet Ollama SLI samples",
            "Sample count for fleet Ollama SLI CLI.",
            "System — fleet",
        ),
        SettingDef(
            "HERMES_FLEET_OLLAMA_SLI_INTERVAL_SEC",
            _SYSTEM,
            _INT,
            "5",
            "Fleet Ollama SLI interval sec",
            "Interval between fleet Ollama SLI samples.",
            "System — fleet",
        ),
    )

    user_extra = (
        SettingDef(
            "HERMES_SLICE_P3_EVIDENCE",
            _USER,
            _BOOL,
            "1",
            "Slice P3 evidence",
            "Emit P3 evidence stages during slice implement.",
            "User — maker runtime",
        ),
        SettingDef(
            "HERMES_SLICE_BRANCH_PREFIX",
            _USER,
            _STR,
            "hermes/run-",
            "Git branch prefix",
            "Prefix for auto-created git branches.",
            "User — git outputs",
        ),
        SettingDef(
            "HERMES_SLICE_PACKET_MAX_CHARS",
            _USER,
            _INT,
            "12000",
            "Slice packet max chars",
            "Max characters in slice context packet.",
            "User — maker runtime",
        ),
        SettingDef(
            "NIMBUSWARE_MAX_PARALLEL_WRITERS",
            _USER,
            _INT,
            "",
            "Max parallel writers",
            "Override hardware governor parallel writer cap.",
            "User — hardware governor",
        ),
        SettingDef(
            "NIMBUSWARE_ALLOW_PARALLEL_CRITICS",
            _USER,
            _BOOL,
            "0",
            "Allow parallel critics",
            "Allow critics to run in parallel under governor.",
            "User — hardware governor",
        ),
        SettingDef(
            "NIMBUSWARE_RESERVE_RAM_GB",
            _USER,
            _INT,
            "2",
            "Reserve RAM GB",
            "RAM reserved for OS outside governor cap.",
            "User — hardware governor",
        ),
        SettingDef(
            "NIMBUSWARE_WORKFLOW_PROFILE",
            _USER,
            _STR,
            "",
            "Workflow profile (legacy)",
            "Legacy alias for default workflow profile.",
            "User — maker runtime",
        ),
        SettingDef(
            "HERMES_WORKFLOW_PROFILE",
            _USER,
            _STR,
            "",
            "Hermes workflow profile (legacy)",
            "Legacy Hermes workflow profile name.",
            "User — maker runtime",
        ),
        SettingDef(
            "HERMES_SLICE_REPLAN_MAX",
            _USER,
            _INT,
            "",
            "Slice replan max attempts",
            "Max replan attempts per slice.",
            "User — maker runtime",
        ),
        SettingDef(
            "HERMES_SLICE_STUB_LOC_PER_FILE",
            _USER,
            _INT,
            "",
            "Slice stub LOC per file",
            "Stub implement LOC budget per file.",
            "User — maker runtime",
        ),
    )

    internal = (
        _internal("HERMES_WORKSPACE", "Dev workspace path override"),
        _internal("HERMES_REFACTOR_FORCE_FAIL", "Force refactor stage fail", kind=_BOOL),
        _internal("HERMES_REFACTOR_STAGE", "Refactor stage override"),
        _internal(
            "HERMES_PARALLEL_WRITER_TEST_DELAY_SECONDS", "Parallel writer test delay", kind=_INT
        ),
        _internal(
            "NIMBUSWARE_HW_FIXTURE",
            "Hardware profile fixture",
            kind=_ENUM,
            choices=("weak", "medium", "strong"),
        ),
        _internal("HERMES_CI_GITHUB_REPO", "CI GitHub repo slug"),
        _internal("HERMES_CI_HEAD_SHA", "CI head SHA"),
        _internal("HERMES_TIMELINE_BASE_URL", "Timeline base URL for CI"),
        _internal("HERMES_FLEET_OLLAMA_SLI_BASE_URL", "Fleet Ollama SLI base URL"),
        _internal("HERMES_FLEET_OLLAMA_SLI_EXPORT_PATH", "Fleet Ollama SLI export path"),
        _internal("HERMES_FLEET_OLLAMA_SLI_HEALTH_PATH", "Fleet Ollama SLI health path"),
        _internal("HERMES_WORKSPACE_SNAPSHOT_DIR", "Workspace snapshot directory"),
        _internal("HERMES_MEMORY_INDEX_DIR", "Memory index directory"),
        _internal("HERMES_SCRAPER_ARTIFACT_DIR", "Scraper artifact directory"),
        _internal("HERMES_PRUNE_STATUS_PATH", "Prune status export path"),
        _internal("HERMES_SQL_QUERY_COUNT_MAX", "SQL query count max", kind=_INT),
        _internal("HERMES_TEST_SQL_QUERY_COUNT", "Test SQL query count flag", kind=_BOOL),
        _internal("HERMES_TEST_WRITER_STAGE_CMD", "Test writer stage command override"),
        _internal("NIMBUSWARE_QUICK_MODE", "Quick mode bootstrap", kind=_BOOL),
    )

    return uc + install + system_extra + user_extra + internal
