from __future__ import annotations

from nimbusware_env.settings_catalog import SettingDef
from nimbusware_env.settings_catalog_extended._factories import (
    _BOOL,
    _INT,
    _STR,
    _SYSTEM,
)


def system_defs() -> tuple[SettingDef, ...]:
    return (
        SettingDef(
            "NIMBUSWARE_PREFLIGHT_JSON_PROBE",
            _SYSTEM,
            _BOOL,
            "0",
            "Preflight JSON probe",
            "Extra JSON probe during Ollama preflight.",
            "System — runtime",
        ),
        SettingDef(
            "NIMBUSWARE_PREFLIGHT_LATENCY_SAMPLES",
            _SYSTEM,
            _INT,
            "1",
            "Preflight latency samples",
            "Sample count for preflight latency (1–20).",
            "System — runtime",
        ),
        SettingDef(
            "NIMBUSWARE_RUN_MYPY",
            _SYSTEM,
            _BOOL,
            "0",
            "Run mypy on verify",
            "Type-check changed paths during verify.",
            "System — verifiers",
        ),
        SettingDef(
            "NIMBUSWARE_SEMGREP_CONFIG",
            _SYSTEM,
            _STR,
            "p/ci",
            "Semgrep config",
            "Semgrep ruleset for verify scan.",
            "System — verifiers",
        ),
        SettingDef(
            "NIMBUSWARE_AGENT_EVALUATOR_AUTO_PROMOTE",
            _SYSTEM,
            _BOOL,
            "0",
            "Agent evaluator auto-promote",
            "Auto-promote agent evaluator findings.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_AGENT_EVALUATOR_AUTO_CREATE",
            _SYSTEM,
            _BOOL,
            "0",
            "Agent evaluator auto-create",
            "Auto-create agent evaluator artifacts.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_AGENT_EVALUATOR_LLM_STUB",
            _SYSTEM,
            _BOOL,
            "0",
            "Agent evaluator LLM stub",
            "Stub LLM for agent evaluator stage.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_PROBATION_AUTO_SHELVE",
            _SYSTEM,
            _BOOL,
            "1",
            "Probation auto-shelve",
            "Auto-shelve personas when probation reliability thresholds fail.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_PROBATION_NOTIFY_BEFORE_PROMOTE",
            _SYSTEM,
            _BOOL,
            "1",
            "Probation promote notice",
            "Emit a finding before auto-promoting probation personas.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_FAST_SLICE",
            _SYSTEM,
            _BOOL,
            "",
            "Fast slice",
            "Empty = workflow YAML; skip optional critic matrix below HIGH severity.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_CODE_INTEL_MAX_FILES",
            _SYSTEM,
            _INT,
            "500",
            "Code intel max files",
            "Maximum Python files scanned when building the code graph / intel bundle.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_CODE_INTEL_INCLUDE_TESTS",
            _SYSTEM,
            _BOOL,
            "",
            "Code intel include tests",
            "When 1, treat test modules under conftest directories as non-orphan seeds.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_PERSONA_COVERAGE_CRITIQUE",
            _SYSTEM,
            _BOOL,
            "",
            "Persona coverage critique",
            "Empty = YAML; force persona coverage critique.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_PERSONA_COVERAGE_CRITIQUE_LLM",
            _SYSTEM,
            _BOOL,
            "",
            "Persona coverage critique LLM",
            "Empty = YAML; LLM for persona coverage critique.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_SELF_REFINEMENT_UNGATED_LOOP",
            _SYSTEM,
            _BOOL,
            "",
            "Self-refinement ungated loop",
            "Empty = YAML; ungated self-refinement loop.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_SELF_REFINEMENT_AUTO_PROMOTE",
            _SYSTEM,
            _BOOL,
            "0",
            "Self-refinement auto-promote",
            "Auto-promote self-refinement findings.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_SELF_REFINEMENT_CRITIQUE_STUB",
            _SYSTEM,
            _BOOL,
            "",
            "Self-refinement critique stub",
            "Empty = YAML; stub self-refinement critique.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_INTEGRATION_ADAPTER_WRITER",
            _SYSTEM,
            _BOOL,
            "",
            "Integration adapter writer",
            "Empty = YAML; integration adapter writer stage.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_INTEGRATION_ADAPTER_LIVE",
            _SYSTEM,
            _BOOL,
            "",
            "Integration adapter live I/O",
            "When on, api_bridge sync_target performs HTTP probes instead of noop.",
            "System — optional stages",
        ),
        SettingDef(
            "NIMBUSWARE_NETWORK_RESILIENCE_CRITIQUE",
            _SYSTEM,
            _BOOL,
            "",
            "Network resilience critique",
            "Empty = YAML; network resilience critique panel.",
            "System — critics",
        ),
        SettingDef(
            "NIMBUSWARE_NETWORK_RESILIENCE_CRITIQUE_LLM",
            _SYSTEM,
            _BOOL,
            "",
            "Network resilience critique LLM",
            "Empty = YAML; LLM for network resilience critique.",
            "System — critics",
        ),
        SettingDef(
            "NIMBUSWARE_PERFORMANCE_CRITIQUE",
            _SYSTEM,
            _BOOL,
            "",
            "Performance critique",
            "Empty = YAML; performance critique panel.",
            "System — critics",
        ),
        SettingDef(
            "NIMBUSWARE_PERFORMANCE_CRITIQUE_LLM",
            _SYSTEM,
            _BOOL,
            "",
            "Performance critique LLM",
            "Empty = YAML; LLM for performance critique.",
            "System — critics",
        ),
        SettingDef(
            "NIMBUSWARE_SECURITY_CRITIQUE",
            _SYSTEM,
            _BOOL,
            "",
            "Security critique",
            "Empty = YAML; security critique panel.",
            "System — critics",
        ),
        SettingDef(
            "NIMBUSWARE_SECURITY_CRITIQUE_LLM",
            _SYSTEM,
            _BOOL,
            "",
            "Security critique LLM",
            "Empty = YAML; LLM for security critique.",
            "System — critics",
        ),
        SettingDef(
            "NIMBUSWARE_TEST_WRITER_STAGE",
            _SYSTEM,
            _BOOL,
            "",
            "Test writer stage",
            "Tri-state override for test writer stage.",
            "System — pipeline",
        ),
        SettingDef(
            "NIMBUSWARE_TEST_WRITER_LLM_BODY",
            _SYSTEM,
            _BOOL,
            "",
            "Test writer LLM body",
            "Tri-state override for test writer LLM body.",
            "System — pipeline",
        ),
        SettingDef(
            "NIMBUSWARE_TEST_WRITER_LLM_STUB",
            _SYSTEM,
            _BOOL,
            "",
            "Test writer LLM stub",
            "Tri-state override for test writer LLM stub.",
            "System — pipeline",
        ),
        SettingDef(
            "NIMBUSWARE_BUNDLE_MEMORY_RANK_WEIGHT",
            _SYSTEM,
            _STR,
            "0.2",
            "Bundle memory rank weight",
            "Weight for bundle memory ranking.",
            "System — memory",
        ),
        SettingDef(
            "NIMBUSWARE_MEMORY_EMBEDDING_MODEL",
            _SYSTEM,
            _STR,
            "",
            "Memory embedding model",
            "Override embedding model for memory index.",
            "System — memory",
        ),
        SettingDef(
            "NIMBUSWARE_SCRAPER_ARTIFACT_MAX_AGE_DAYS",
            _SYSTEM,
            _INT,
            "",
            "Scraper artifact max age days",
            "Retention max age for scraper artifacts.",
            "System — egress",
        ),
        SettingDef(
            "NIMBUSWARE_FLEET_OLLAMA_SLI_SAMPLES",
            _SYSTEM,
            _INT,
            "60",
            "Fleet Ollama SLI samples",
            "Sample count for fleet Ollama SLI CLI.",
            "System — fleet",
        ),
        SettingDef(
            "NIMBUSWARE_FLEET_OLLAMA_SLI_INTERVAL_SEC",
            _SYSTEM,
            _INT,
            "5",
            "Fleet Ollama SLI interval sec",
            "Interval between fleet Ollama SLI samples.",
            "System — fleet",
        ),
        SettingDef(
            "NIMBUSWARE_FLEET_OLLAMA_SLI_TIMEOUT_SEC",
            _SYSTEM,
            _INT,
            "30",
            "Fleet Ollama SLI probe timeout sec",
            "HTTP timeout per fleet Ollama SLI health probe.",
            "System — fleet",
        ),
        SettingDef(
            "NIMBUSWARE_FLEET_QUEUE_BACKPRESSURE_DEPTH",
            _SYSTEM,
            _INT,
            "100",
            "Fleet queue pending depth cap",
            "Pause verify dispatch when Redis pending depth exceeds cap.",
            "System — fleet",
        ),
        SettingDef(
            "NIMBUSWARE_FLEET_QUEUE_BACKPRESSURE_IN_FLIGHT",
            _SYSTEM,
            _INT,
            "20",
            "Fleet queue in-flight cap",
            "Pause verify dispatch when in-flight tasks exceed cap.",
            "System — fleet",
        ),
        SettingDef(
            "NIMBUSWARE_SCRAPER_ARTIFACT_OBJECT_STORE_PRUNE",
            _SYSTEM,
            _BOOL,
            "0",
            "Prune scraper artifacts from object store",
            "Enable retention prune against object-store primary backend.",
            "System — scraper",
        ),
    )
