#!/usr/bin/env python3
"""Count lines of source in the Nimbusware repo, excluding generated artifacts.

Usage:
  poetry run python scripts/count_loc.py
  poetry run python scripts/count_loc.py --git-tracked
  poetry run python scripts/count_loc.py --json
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Directory names skipped anywhere under the tree (build tooling, caches, VCS).
SKIP_DIR_NAMES = frozenset(
    {
        ".git",
        ".venv",
        "venv",
        "env",
        "ENV",
        "node_modules",
        "__pycache__",
        ".pytest_cache",
        ".mypy_cache",
        ".ruff_cache",
        ".vite",
        "dist",
        "build",
        "develop-eggs",
        "downloads",
        "eggs",
        ".eggs",
        "lib",
        "lib64",
        "parts",
        "sdist",
        "var",
        "wheels",
        "pip-wheel-metadata",
        "share",
        ".cursor",
        ".hermes",
        ".cache",
        "logs",
        "benchmarks",
        "test-results",
        "playwright-report",
        "blob-report",
        ".ipynb_checkpoints",
        # Derived indexes (rebuilt locally; not hand-written source)
        "index",
    }
)

# Path prefixes (relative to repo root) that are entirely out of scope.
SKIP_PATH_PREFIXES = (
    "configs/memory/index/",
    "configs/memory/fleet/",
    "configs/bundles/index/",
    "packages/nimbusware_maker/ui/",
    "packages/nimbusware_console/pages/",
    ".streamlit/",
)

# Programming-language extensions (default metric).
LANG_EXTENSIONS = frozenset(
    {
        ".py",
        ".js",
        ".ts",
        ".tsx",
        ".jsx",
        ".mjs",
        ".cjs",
        ".css",
        ".html",
        ".htm",
        ".sql",
        ".sh",
        ".bash",
        ".ps1",
    }
)

# Optional buckets (not generated; reported separately with flags).
DOC_EXTENSIONS = frozenset({".md"})
CONFIG_EXTENSIONS = frozenset({".yaml", ".yml", ".toml", ".json"})

# Lockfiles and manifests are not "code" for this metric.
SKIP_FILE_NAMES = frozenset(
    {
        "poetry.lock",
        "package-lock.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        "Cargo.lock",
    }
)

# Filename patterns for vendored / minified bundles.
SKIP_FILE_GLOBS = (
    re.compile(r"\.min\.(js|css)$", re.I),
    re.compile(r"\.bundle\.(js|css)$", re.I),
    re.compile(r"-[A-Za-z0-9]{6,}\.(js|css)$"),  # Vite hashed assets under dist/
)

GENERATED_HEADER_MARKERS = (
    "generated by scripts/openapi_to_ts.py",
    "generated by openapi",
    "auto-generated",
    "autogenerated",
    "do not edit",
)


@dataclass
class FileStats:
    path: str
    extension: str
    physical: int = 0
    non_blank: int = 0
    generated: bool = False


@dataclass
class Totals:
    files: int = 0
    physical: int = 0
    non_blank: int = 0
    by_extension: dict[str, dict[str, int]] = field(default_factory=lambda: defaultdict(lambda: {"files": 0, "physical": 0, "non_blank": 0}))


def _is_under_skip_prefix(rel_posix: str) -> bool:
    return any(rel_posix.startswith(p) for p in SKIP_PATH_PREFIXES)


def _allowed_extensions(include_docs: bool, include_config: bool) -> frozenset[str]:
    exts = set(LANG_EXTENSIONS)
    if include_docs:
        exts |= DOC_EXTENSIONS
    if include_config:
        exts |= CONFIG_EXTENSIONS
    return frozenset(exts)


def _should_skip_file(rel: Path, allowed: frozenset[str]) -> bool:
    name = rel.name
    if name in SKIP_FILE_NAMES:
        return True
    if name in {"Dockerfile", "Makefile"}:
        pass
    elif rel.suffix.lower() in {".typed"} or name == "py.typed":
        return True
    elif rel.suffix.lower() not in allowed:
        return True
    rel_s = rel.as_posix()
    if _is_under_skip_prefix(rel_s):
        return True
    # Built Admin SPA assets (committed dist/); source lives in src/.
    if "/dist/" in rel_s and rel.suffix.lower() in {".js", ".css", ".html", ".map"}:
        return True
    if "/dist/" in rel_s:
        for pat in SKIP_FILE_GLOBS:
            if pat.search(name):
                return True
    if name.endswith(".min.js") or name.endswith(".min.css"):
        return True
    if name == "alpine.min.js":
        return True
    return False


def _looks_generated(text: str) -> bool:
    head = "\n".join(text.splitlines()[:8]).lower()
    return any(m in head for m in GENERATED_HEADER_MARKERS)


def _iter_paths(git_tracked: bool) -> list[Path]:
    if git_tracked:
        proc = subprocess.run(
            ["git", "-C", str(ROOT), "ls-files", "-z"],
            check=True,
            capture_output=True,
        )
        out = proc.stdout.decode("utf-8", errors="replace")
        return [ROOT / p for p in out.split("\0") if p]
    paths: list[Path] = []
    for p in ROOT.rglob("*"):
        if not p.is_file():
            continue
        rel = p.relative_to(ROOT)
        if any(part in SKIP_DIR_NAMES for part in rel.parts):
            continue
        if _is_under_skip_prefix(rel.as_posix()):
            continue
        paths.append(p)
    return paths


def _count_file(path: Path, allowed: frozenset[str]) -> FileStats | None:
    rel = path.relative_to(ROOT)
    if _should_skip_file(rel, allowed):
        return None
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    physical = len(text.splitlines())
    non_blank = sum(1 for line in text.splitlines() if line.strip())
    ext = rel.suffix.lower() or "(no ext)"
    return FileStats(
        path=rel.as_posix(),
        extension=ext,
        physical=physical,
        non_blank=non_blank,
        generated=_looks_generated(text),
    )


def collect(
    git_tracked: bool,
    *,
    include_docs: bool,
    include_config: bool,
) -> tuple[list[FileStats], list[FileStats]]:
    allowed = _allowed_extensions(include_docs, include_config)
    source: list[FileStats] = []
    generated: list[FileStats] = []
    for path in _iter_paths(git_tracked):
        if not path.is_file():
            continue
        rel = path.relative_to(ROOT)
        if any(part in SKIP_DIR_NAMES for part in rel.parts):
            continue
        stats = _count_file(path, allowed)
        if stats is None:
            continue
        if stats.generated:
            generated.append(stats)
        else:
            source.append(stats)
    return source, generated


def _summarize(files: list[FileStats]) -> Totals:
    t = Totals()
    for f in files:
        t.files += 1
        t.physical += f.physical
        t.non_blank += f.non_blank
        bucket = t.by_extension[f.extension]
        bucket["files"] += 1
        bucket["physical"] += f.physical
        bucket["non_blank"] += f.non_blank
    return t


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--git-tracked",
        action="store_true",
        help="Only count files returned by git ls-files (default: walk working tree)",
    )
    parser.add_argument("--json", action="store_true", help="Emit machine-readable summary")
    parser.add_argument(
        "--include-docs",
        action="store_true",
        help="Count Markdown (.md) in addition to programming languages",
    )
    parser.add_argument(
        "--include-config",
        action="store_true",
        help="Count YAML/TOML/JSON config in addition to programming languages",
    )
    args = parser.parse_args()

    source, generated = collect(
        args.git_tracked,
        include_docs=args.include_docs,
        include_config=args.include_config,
    )
    totals = _summarize(source)
    gen_totals = _summarize(generated)

    if args.json:
        payload = {
            "root": str(ROOT),
            "git_tracked": args.git_tracked,
            "source": {
                "files": totals.files,
                "physical_lines": totals.physical,
                "non_blank_lines": totals.non_blank,
                "by_extension": dict(totals.by_extension),
            },
            "generated_marked": {
                "files": gen_totals.files,
                "physical_lines": gen_totals.physical,
                "non_blank_lines": gen_totals.non_blank,
            },
        }
        print(json.dumps(payload, indent=2, sort_keys=True))
        return 0

    mode = "git-tracked files" if args.git_tracked else "working tree (excl. ignored dirs)"
    print(f"Nimbusware LOC - {mode}")
    print(f"Root: {ROOT}")
    print()
    scope = "programming languages (.py, .js/.ts, .css, .html, .sql, shell)"
    if args.include_docs:
        scope += " + Markdown"
    if args.include_config:
        scope += " + YAML/TOML/JSON"
    print(f"Counted: {scope}")
    print("Excluded: dist/, node_modules/, __pycache__, .venv, lockfiles,")
    print("  *.min.js, Vite hashed bundles, derived FAISS index dirs, retired ui/ trees.")
    print()
    print(f"Source files:     {totals.files:,}")
    print(f"Physical lines:   {totals.physical:,}")
    print(f"Non-blank lines:  {totals.non_blank:,}  (typical 'LOC' metric)")
    if gen_totals.files:
        print()
        print(f"Also skipped {gen_totals.files} file(s) with generated headers ({gen_totals.physical:,} lines).")
    print()
    print("By extension (non-blank lines):")
    rows = sorted(totals.by_extension.items(), key=lambda kv: -kv[1]["non_blank"])
    for ext, bucket in rows:
        print(f"  {ext:8}  {bucket['non_blank']:>8,}  ({bucket['files']} files)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
