#!/usr/bin/env python3

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "packages" / "nimbusware_admin_ui" / "src" / "api" / "schema.d.ts"


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    stub = """// Generated by scripts/openapi_to_ts.py — expand via openapi-typescript when needed.
export type RunSummary = {
  run_id: string;
  status?: string;
  workflow_profile?: string;
  created_at?: string;
};

export type RunsListResponse = {
  runs?: RunSummary[];
  items?: RunSummary[];
  next_cursor?: string | null;
};
"""
    OUT.write_text(stub, encoding="utf-8")
    print(json.dumps({"ok": True, "path": str(OUT)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
