#!/usr/bin/env python3

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "packages" / "nimbusware_admin_ui" / "src" / "api" / "schema.d.ts"
OPENAPI_JSON = OUT.parent / "openapi.json"


def _manual_stub() -> str:
    return """// Generated by scripts/openapi_to_ts.py — expand via openapi-typescript when needed.
export type RunSummary = {
  status: string;
  workflow_profile?: string | null;
  event_count: number;
  latest_event_type: string;
  terminal_event_type?: string | null;
  findings_count: number;
  has_escalation: boolean;
  run_created_metadata?: Record<string, unknown>;
  persona_assignment?: Record<string, unknown> | null;
};

export type RunsListResponse = {
  run_ids?: string[];
  total?: number;
  has_more?: boolean;
  limit?: number;
  offset?: number;
  order?: "newest_first" | "oldest_first";
  include_summary?: number;
  workflow_profile?: string | null;
  workflow_profile_prefix?: string | null;
  created_after?: string | null;
  created_before?: string | null;
  has_escalation?: number | null;
  summaries?: Record<string, RunSummary>;
  next_cursor?: string | null;
  status?: string | null;
  runs?: RunSummary[];
  items?: RunSummary[];
};

export type PolicyDiffResponse = {
  run_a: string;
  run_b: string;
  identical: boolean;
  changed_count: number;
  changed: Record<string, unknown>[];
  gate_outcome?: Record<string, unknown> | null;
};
"""


def _export_openapi() -> dict | None:
    try:
        from nimbusware_api.app import app
    except ImportError:
        return None
    return app.openapi()


def _try_openapi_typescript(openapi_path: Path) -> bool:
    if shutil.which("npx") is None:
        return False
    try:
        proc = subprocess.run(
            [
                "npx",
                "--yes",
                "openapi-typescript",
                str(openapi_path),
                "-o",
                str(OUT),
            ],
            capture_output=True,
            text=True,
            timeout=180,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False
    return proc.returncode == 0


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    schema = _export_openapi()
    source = "manual"
    if schema is not None:
        OPENAPI_JSON.write_text(json.dumps(schema, indent=2), encoding="utf-8")
        if _try_openapi_typescript(OPENAPI_JSON):
            source = "openapi-typescript"
        else:
            OUT.write_text(_manual_stub(), encoding="utf-8")
    else:
        OUT.write_text(_manual_stub(), encoding="utf-8")

    print(json.dumps({"ok": True, "path": str(OUT), "openapi": str(OPENAPI_JSON), "source": source}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
