#!/usr/bin/env python3

from __future__ import annotations

import json
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "packages" / "nimbusware_admin_ui" / "src" / "api" / "schema.d.ts"
OPENAPI_JSON = OUT.parent / "openapi.json"


def _manual_stub() -> str:
    return """// Generated by scripts/codegen/openapi_to_ts.py — expand via openapi-typescript when needed.
export type RunSummary = {
  status: string;
  workflow_profile?: string | null;
  event_count: number;
  latest_event_type: string;
  terminal_event_type?: string | null;
  findings_count: number;
  has_escalation: boolean;
  run_created_metadata?: Record<string, unknown>;
  persona_assignment?: Record<string, unknown> | null;
};

export type RunsListResponse = {
  run_ids?: string[];
  total?: number;
  has_more?: boolean;
  limit?: number;
  offset?: number;
  order?: "newest_first" | "oldest_first";
  include_summary?: number;
  workflow_profile?: string | null;
  workflow_profile_prefix?: string | null;
  created_after?: string | null;
  created_before?: string | null;
  has_escalation?: number | null;
  summaries?: Record<string, RunSummary>;
  next_cursor?: string | null;
  status?: string | null;
  runs?: RunSummary[];
  items?: RunSummary[];
};

export type PolicyDiffResponse = {
  run_a: string;
  run_b: string;
  identical: boolean;
  changed_count: number;
  changed: Record<string, unknown>[];
  gate_outcome?: Record<string, unknown> | null;
};
"""


def _export_openapi() -> dict | None:
    try:
        from nimbusware_api.app import app
    except ImportError:
        return None
    return app.openapi()


def _npx_executable() -> str | None:
    return shutil.which("npx") or shutil.which("npx.cmd")


def _is_full_openapi_schema() -> bool:
    if not OUT.is_file():
        return False
    text = OUT.read_text(encoding="utf-8")
    if text.startswith("// Generated by scripts/codegen/openapi_to_ts.py"):
        return False
    return OUT.stat().st_size > len(_manual_stub())


def _try_openapi_typescript(openapi_path: Path) -> bool:
    npx = _npx_executable()
    if npx is None:
        return False
    args = [npx, "--yes", "openapi-typescript", str(openapi_path.resolve()), "-o", str(OUT.resolve())]
    for _attempt in range(2):
        try:
            if platform.system() == "Windows" and npx.lower().endswith(".cmd"):
                proc = subprocess.run(
                    subprocess.list2cmdline(args),
                    shell=True,
                    capture_output=True,
                    text=True,
                    timeout=180,
                    check=False,
                )
            else:
                proc = subprocess.run(
                    args,
                    capture_output=True,
                    text=True,
                    timeout=180,
                    check=False,
                )
        except (OSError, subprocess.TimeoutExpired):
            continue
        if proc.returncode != 0:
            sys.stderr.write(proc.stderr or proc.stdout or "openapi-typescript failed\n")
            continue
        if OUT.is_file() and OUT.stat().st_size > len(_manual_stub()):
            return True
    return False


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    schema = _export_openapi()
    source = "manual"
    if schema is not None:
        OPENAPI_JSON.write_text(json.dumps(schema, indent=2), encoding="utf-8")
        if _try_openapi_typescript(OPENAPI_JSON) or _is_full_openapi_schema():
            source = "openapi-typescript"
        else:
            OUT.write_text(_manual_stub(), encoding="utf-8")
    else:
        OUT.write_text(_manual_stub(), encoding="utf-8")

    require_full = os.environ.get("NIMBUSWARE_OPENAPI_TS_REQUIRE_FULL", "").strip().lower() in {
        "1",
        "true",
        "yes",
    }
    if require_full and source != "openapi-typescript":
        sys.stderr.write("NIMBUSWARE_OPENAPI_TS_REQUIRE_FULL set but openapi-typescript unavailable\n")
        return 1

    print(json.dumps({"ok": True, "path": str(OUT), "openapi": str(OPENAPI_JSON), "source": source}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
